const { Plugin, ItemView, Notice, PluginSettingTab, Setting, normalizePath, setIcon } = require('obsidian');

const VIEW_TYPE_PERSONAL_FUNDS = 'personal-funds-view';
const DEFAULT_DATA_FOLDER = 'Personal_funds';
const DATABASE_FILE_NAME = 'records.json';
const LEGACY_PLUGIN_DATA_PATH = '.obsidian/plugins/milin-simple-finance/data.json';

const SUMMARY_NOTES = [
  { key: 'currentAccount', slug: 'current-account', type: 'account', recordTypes: ['income', 'expense', 'repay_credit', 'lend_out', 'collect_loan', 'account_adjust', 'borrow_in', 'repay_debt'] },
  { key: 'creditCard', slug: 'credit-card', type: 'credit', recordTypes: ['credit_expense', 'repay_credit'] },
  { key: 'expense', slug: 'expense', type: 'expense', recordTypes: ['expense', 'credit_expense'] },
  { key: 'income', slug: 'income', type: 'income', recordTypes: ['income'] },
  { key: 'loanOut', slug: 'lending', type: 'loan', recordTypes: ['lend_out', 'collect_loan'] }
];

const TYPES = [
  { id: 'income', labels: { zh: '收入', en: 'Income' }, tone: 'income' },
  { id: 'expense', labels: { zh: '支出', en: 'Expense' }, tone: 'expense' },
  { id: 'credit_expense', labels: { zh: '信用卡支出', en: 'Credit expense' }, tone: 'credit' },
  { id: 'repay_credit', labels: { zh: '还信用卡', en: 'Repay credit card' }, tone: 'credit' },
  { id: 'lend_out', labels: { zh: '借出', en: 'Lend out' }, tone: 'loan' },
  { id: 'collect_loan', labels: { zh: '收回借出', en: 'Collect loan' }, tone: 'loan' },
  { id: 'account_adjust', labels: { zh: '当前账户调整', en: 'Account adjustment' }, tone: 'neutral' }
];

const TYPE_MAP = Object.fromEntries(TYPES.map(t => [t.id, t]));

const DEFAULT_CATEGORIES = {
  zh: ['吃饭', '交通', '设备/元器件', '学习', '接单', '工资', '信用卡', '借出', '初始余额', '人情', '其他'],
  en: ['Food', 'Transport', 'Devices/Parts', 'Learning', 'Freelance', 'Salary', 'Credit card', 'Lending', 'Initial balance', 'Social', 'Other']
};

const I18N = {
  zh: {
    title: 'Personal Funds',
    languageName: '中文',
    languageSwitch: 'EN',
    switchTitle: 'Switch to English',
    currentAccount: '当前账户',
    creditCard: '信用卡',
    expense: '支出',
    income: '收入',
    loanOut: '借出',
    amount: '金额',
    personPlaceholder: '对象：谁',
    notePlaceholder: '备注，可不填',
    save: '保存',
    updateDashboard: 'MD',
    createCanvas: 'Canvas',
    readDatabase: 'Read',
    recentRecords: '最近记录',
    recordCount: count => `共 ${count} 条记录`,
    noRecords: '还没有记录。',
    uncategorized: '未分类',
    self: '自己',
    emptyNote: '-',
    delete: '删除',
    amountNotice: '请输入大于 0 的金额',
    savedNotice: '已保存，并已更新资金看板',
    deletedNotice: '已删除，并已更新资金看板',
    dashboardUpdatedNotice: '资金看板.md 已更新',
    canvasUpdatedNotice: '资金看板.canvas 已创建/更新',
    databaseReadNotice: '已从数据库读取记录',
    databaseSavedNotice: '数据库已保存',
    databaseMissingNotice: '还没有数据库文件，会在下次保存记录时创建',
    tip: '金额位数较多时，顶部数字会自动缩小，保证 5 个卡片稳定显示。',
    dashboardTitle: '资金看板',
    autoGenerated: '由 Personal Funds 自动生成。更新时间：',
    databaseFolderName: '数据文件夹',
    databaseFolderDesc: '记录数据库、资金看板、Canvas 和单项记录会保存在这个文件夹。',
    summaryAfterCredit: value => `扣除信用卡提醒：${formatMoney(value)}`,
    overview: '总览',
    currentMonth: '本月',
    item: '项目',
    value: '金额',
    monthlyAccountChange: '本月当前账户变化',
    monthlyCreditChange: '本月信用卡新增/减少',
    monthlyExpense: '本月支出',
    monthlyIncome: '本月收入',
    monthlyLoanLeft: '本月借出未收回',
    rulesTitle: '口径说明',
    ruleCurrent: '当前账户 = 收入 - 支出 - 还信用卡 - 借出 + 收回借出 + 当前账户调整。',
    ruleCredit: '信用卡 = 信用卡支出 - 还信用卡。',
    ruleExpense: '支出 = 现金支出 + 信用卡支出。',
    ruleLoan: '借出 = 借出 - 收回借出。',
    date: '日期',
    type: '类型',
    category: '分类',
    person: '对象',
    note: '备注',
    canvasGuideTitle: '使用方法',
    canvasGuide1: '点击左侧钱包图标记账',
    canvasGuide2: '保存后自动更新“资金看板.md”',
    canvasGuide3: '在 Canvas 中查看汇总',
    typeIntroTitle: '类型',
    guideIncome: '收入：钱进入当前账户',
    guideExpense: '支出：当前账户直接花钱',
    guideCreditExpense: '信用卡支出：信用卡欠款增加',
    guideRepayCredit: '还信用卡：当前账户减少，信用卡欠款减少',
    guideLendOut: '借出：别人欠你钱',
    guideCollectLoan: '收回借出：别人还你钱',
    guideAdjust: '当前账户调整：设置初始余额或修正余额',
    legacyBorrowIn: '负债/借入',
    legacyRepayDebt: '负债/还债'
  },
  en: {
    title: 'Personal Funds',
    languageName: 'English',
    languageSwitch: '中文',
    switchTitle: '切换到中文',
    currentAccount: 'Current account',
    creditCard: 'Credit card',
    expense: 'Expense',
    income: 'Income',
    loanOut: 'Lending',
    amount: 'Amount',
    personPlaceholder: 'Person',
    notePlaceholder: 'Note, optional',
    save: 'Save',
    updateDashboard: 'MD',
    createCanvas: 'Canvas',
    readDatabase: 'Read',
    recentRecords: 'Recent records',
    recordCount: count => `${count} record${count === 1 ? '' : 's'}`,
    noRecords: 'No records yet.',
    uncategorized: 'Uncategorized',
    self: 'Self',
    emptyNote: '-',
    delete: 'Delete',
    amountNotice: 'Enter an amount greater than 0',
    savedNotice: 'Saved and dashboard updated',
    deletedNotice: 'Deleted and dashboard updated',
    dashboardUpdatedNotice: 'Funds dashboard.md updated',
    canvasUpdatedNotice: 'Funds dashboard canvas created/updated',
    databaseReadNotice: 'Records loaded from database',
    databaseSavedNotice: 'Database saved',
    databaseMissingNotice: 'No database file yet. It will be created the next time you save a record.',
    tip: 'Longer numbers automatically shrink so all 5 summary cards stay stable.',
    dashboardTitle: 'Funds dashboard',
    autoGenerated: 'Auto-generated by Personal Funds. Updated at: ',
    databaseFolderName: 'Data folder',
    databaseFolderDesc: 'The record database, funds dashboard, Canvas, and summary notes are saved in this folder.',
    summaryAfterCredit: value => `After credit reminder: ${formatMoney(value)}`,
    overview: 'Overview',
    currentMonth: 'This month',
    item: 'Item',
    value: 'Amount',
    monthlyAccountChange: 'Monthly account change',
    monthlyCreditChange: 'Monthly credit card change',
    monthlyExpense: 'Monthly expense',
    monthlyIncome: 'Monthly income',
    monthlyLoanLeft: 'Monthly lending not collected',
    rulesTitle: 'Calculation rules',
    ruleCurrent: 'Current account = income - expense - credit card repayments - lending + collected loans + account adjustments.',
    ruleCredit: 'Credit card = credit card expenses - credit card repayments.',
    ruleExpense: 'Expense = cash expense + credit card expense.',
    ruleLoan: 'Lending = lend out - collect loan.',
    date: 'Date',
    type: 'Type',
    category: 'Category',
    person: 'Person',
    note: 'Note',
    canvasGuideTitle: 'How to use',
    canvasGuide1: 'Click the wallet icon on the left to add a record',
    canvasGuide2: 'The funds dashboard.md note updates automatically after saving',
    canvasGuide3: 'View the summary in Canvas',
    typeIntroTitle: 'Types',
    guideIncome: 'Income: money enters your current account',
    guideExpense: 'Expense: spend directly from your current account',
    guideCreditExpense: 'Credit expense: credit card debt increases',
    guideRepayCredit: 'Repay credit card: current account decreases and card debt decreases',
    guideLendOut: 'Lend out: someone owes you money',
    guideCollectLoan: 'Collect loan: someone repays you',
    guideAdjust: 'Account adjustment: set initial balance or correct balance',
    legacyBorrowIn: 'Borrow in',
    legacyRepayDebt: 'Repay debt'
  }
};

const DASHBOARD_FILE_NAME = 'Funds dashboard.md';
const CANVAS_FILE_NAME = 'Funds dashboard.canvas';

function pad2(n) {
  return String(n).padStart(2, '0');
}

function localDateParts(date = new Date()) {
  const yyyy = date.getFullYear();
  const mm = pad2(date.getMonth() + 1);
  const dd = pad2(date.getDate());
  const hh = pad2(date.getHours());
  const mi = pad2(date.getMinutes());
  return { date: `${yyyy}-${mm}-${dd}`, time: `${hh}:${mi}` };
}

function formatMoney(value) {
  const num = Number(value || 0);
  return num.toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2
  });
}

function signedMoney(value, positivePrefix = '+') {
  const num = Number(value || 0);
  const abs = Math.abs(num);
  const sign = num > 0 ? positivePrefix : num < 0 ? '-' : '';
  return `${sign}${formatMoney(abs)}`;
}

function valueFontSize(text) {
  const len = String(text).length;
  if (len <= 4) return '30px';
  if (len <= 7) return '28px';
  if (len <= 9) return '25px';
  if (len <= 12) return '22px';
  return '19px';
}

module.exports = class PersonalFundsPlugin extends Plugin {
  async onload() {
    this.data = await this.loadData();
    if (!this.data || typeof this.data !== 'object') {
      this.data = { records: [], settings: { language: 'zh' } };
    }
    if (!Array.isArray(this.data.records)) {
      this.data.records = [];
    }
    if (!this.data.settings || typeof this.data.settings !== 'object') {
      this.data.settings = {};
    }
    if (!['zh', 'en'].includes(this.data.settings.language)) {
      this.data.settings.language = 'zh';
    }
    if (!this.data.settings.dataFolder || typeof this.data.settings.dataFolder !== 'string') {
      this.data.settings.dataFolder = DEFAULT_DATA_FOLDER;
    }
    await this.loadDatabaseOnStartup();
    await this.saveData(this.data);
    this.addSettingTab(new PersonalFundsSettingTab(this.app, this));

    this.registerView(
      VIEW_TYPE_PERSONAL_FUNDS,
      leaf => new FinanceView(leaf, this)
    );

    this.addRibbonIcon('wallet-cards', this.t('title'), () => {
      this.openFinanceView();
    });

    this.addCommand({
      id: 'open-personal-funds',
      name: 'Open personal funds',
      callback: () => this.openFinanceView()
    });

    this.addCommand({
      id: 'update-funds-dashboard',
      name: 'Update funds dashboard markdown',
      callback: async () => {
        await this.updateDashboardNote();
        new Notice(this.t('dashboardUpdatedNotice'));
      }
    });

    this.addCommand({
      id: 'create-funds-canvas',
      name: 'Create or update funds canvas',
      callback: async () => {
        await this.updateDashboardNote();
        await this.createOrUpdateCanvas();
        new Notice(this.t('canvasUpdatedNotice'));
      }
    });

    this.addCommand({
      id: 'read-funds-database',
      name: 'Read funds database',
      callback: async () => {
        const loaded = await this.readDatabase();
        if (loaded) {
          new Notice(this.t('databaseReadNotice'));
          this.refreshViews();
        }
      }
    });
  }

  async openFinanceView() {
    let leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_PERSONAL_FUNDS)[0];
    if (!leaf) {
      leaf = this.app.workspace.getLeaf('tab');
      await leaf.setViewState({
        type: VIEW_TYPE_PERSONAL_FUNDS,
        active: true
      });
    }
    this.app.workspace.revealLeaf(leaf);
  }

  getDataFolder() {
    const folder = String(this.data?.settings?.dataFolder || DEFAULT_DATA_FOLDER).trim();
    return normalizePath(folder || DEFAULT_DATA_FOLDER).replace(/^\/+|\/+$/g, '');
  }

  getVaultPath(fileName) {
    return normalizePath(`${this.getDataFolder()}/${fileName}`);
  }

  getDatabasePath() {
    return this.getVaultPath(DATABASE_FILE_NAME);
  }

  getDashboardPath() {
    return this.getVaultPath(DASHBOARD_FILE_NAME);
  }

  getCanvasPath() {
    return this.getVaultPath(CANVAS_FILE_NAME);
  }

  getSummaryNotePath(note) {
    return this.getVaultPath(`Summary/${note.slug}.md`);
  }

  async loadDatabaseOnStartup() {
    try {
      const loaded = await this.readDatabase(false);
      if (loaded) return;
    } catch (error) {
      console.error('Personal Funds: failed to read database on startup', error);
      new Notice('Personal Funds database read failed. Check records.json.');
    }

    const migrated = await this.tryReadLegacyPluginData();
    if (migrated) {
      await this.writeDatabase();
      return;
    }

    if (this.getRecords().length > 0) {
      await this.writeDatabase();
    }
  }

  async readDatabase(showMissingNotice = true) {
    const path = this.getDatabasePath();
    const exists = await this.app.vault.adapter.exists(path);
    if (!exists) {
      if (showMissingNotice) new Notice(this.t('databaseMissingNotice'));
      return false;
    }

    const raw = await this.app.vault.adapter.read(path);
    const parsed = JSON.parse(raw);
    const records = Array.isArray(parsed) ? parsed : parsed.records;
    if (!Array.isArray(records)) {
      throw new Error(`Invalid Personal Funds database: ${path}`);
    }

    this.data.records = records;
    if (parsed.settings && typeof parsed.settings === 'object') {
      this.data.settings = { ...this.data.settings, ...parsed.settings, dataFolder: this.getDataFolder() };
    }
    await this.saveData(this.data);
    return true;
  }

  async tryReadLegacyPluginData() {
    const exists = await this.app.vault.adapter.exists(LEGACY_PLUGIN_DATA_PATH);
    if (!exists) return false;

    try {
      const parsed = JSON.parse(await this.app.vault.adapter.read(LEGACY_PLUGIN_DATA_PATH));
      if (!Array.isArray(parsed.records) || parsed.records.length === 0) return false;
      this.data.records = parsed.records;
      this.data.settings = { ...this.data.settings, ...(parsed.settings || {}) };
      if (!this.data.settings.dataFolder) this.data.settings.dataFolder = DEFAULT_DATA_FOLDER;
      return true;
    } catch (error) {
      console.error('Personal Funds: failed to read legacy plugin data', error);
      return false;
    }
  }

  async writeDatabase() {
    const payload = {
      version: 1,
      updatedAt: new Date().toISOString(),
      settings: {
        language: this.getLanguage()
      },
      records: this.getRecords()
    };
    await this.writeVaultFile(this.getDatabasePath(), JSON.stringify(payload, null, 2));
  }

  refreshViews() {
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_PERSONAL_FUNDS)) {
      leaf.view?.render?.();
    }
  }

  async openMarkdownSource(path) {
    const file = this.app.vault.getAbstractFileByPath(normalizePath(path));
    if (!file) {
      new Notice(this.t('dashboardUpdatedNotice'));
      return;
    }

    const leaf = this.app.workspace.getLeaf('tab');
    await leaf.openFile(file, {
      active: true,
      state: { mode: 'source' }
    });
  }

  async openDashboardNote() {
    await this.updateDashboardNote();
    await this.openMarkdownSource(this.getDashboardPath());
  }

  async openSummaryNote(note) {
    await this.updateSummaryNote(note);
    await this.openMarkdownSource(this.getSummaryNotePath(note));
  }

  getLanguage() {
    return this.data?.settings?.language || 'zh';
  }

  t(key, ...args) {
    const lang = this.getLanguage();
    const value = I18N[lang]?.[key] ?? I18N.zh[key] ?? key;
    return typeof value === 'function' ? value(...args) : value;
  }

  async toggleLanguage() {
    this.data.settings.language = this.getLanguage() === 'zh' ? 'en' : 'zh';
    await this.saveData(this.data);
    await this.writeDatabase();
  }

  getCategories() {
    return DEFAULT_CATEGORIES[this.getLanguage()] || DEFAULT_CATEGORIES.zh;
  }

  async addRecord(record) {
    this.data.records.unshift(record);
    await this.saveData(this.data);
    await this.writeDatabase();
    await this.updateDashboardNote();
  }

  async deleteRecord(id) {
    this.data.records = this.data.records.filter(r => r.id !== id);
    await this.saveData(this.data);
    await this.writeDatabase();
    await this.updateDashboardNote();
  }

  getRecords() {
    return this.data.records || [];
  }

  getTypeLabel(type) {
    const lang = this.getLanguage();
    return TYPE_MAP[type]?.labels?.[lang] || TYPE_MAP[type]?.labels?.zh || this.getLegacyTypeLabel(type);
  }

  getTypeTone(type) {
    return TYPE_MAP[type]?.tone || 'neutral';
  }

  getLegacyTypeLabel(type) {
    const legacy = {
      borrow_in: this.t('legacyBorrowIn'),
      repay_debt: this.t('legacyRepayDebt'),
      lend_out: this.getTypeLabel('lend_out'),
      collect_loan: this.getTypeLabel('collect_loan')
    };
    return legacy[type] || type;
  }

  emptySummary() {
    return {
      currentAccount: 0,
      creditCard: 0,
      expense: 0,
      income: 0,
      loanLeft: 0,
      collectLoan: 0,
      accountAdjust: 0
    };
  }

  applyRecordToSummary(summary, record) {
    const amount = Number(record.amount) || 0;

    switch (record.type) {
      case 'income':
        summary.income += amount;
        summary.currentAccount += amount;
        break;

      case 'expense':
        summary.expense += amount;
        summary.currentAccount -= amount;
        break;

      case 'credit_expense':
        summary.expense += amount;
        summary.creditCard += amount;
        break;

      case 'repay_credit':
        summary.currentAccount -= amount;
        summary.creditCard -= amount;
        break;

      case 'lend_out':
        summary.loanLeft += amount;
        summary.currentAccount -= amount;
        break;

      case 'collect_loan':
        summary.collectLoan += amount;
        summary.loanLeft -= amount;
        summary.currentAccount += amount;
        break;

      case 'account_adjust':
        summary.accountAdjust += amount;
        summary.currentAccount += amount;
        break;

      case 'borrow_in':
        summary.currentAccount += amount;
        break;

      case 'repay_debt':
        summary.currentAccount -= amount;
        break;

      default:
        break;
    }
  }

  getSummary(records = this.getRecords()) {
    const summary = this.emptySummary();
    for (const r of records) {
      this.applyRecordToSummary(summary, r);
    }
    return summary;
  }

  getCurrentMonthRecords() {
    const { date } = localDateParts();
    const ym = date.slice(0, 7);
    return this.getRecords().filter(r => String(r.date || '').startsWith(ym));
  }

  getCurrentMonthSummary() {
    return this.getSummary(this.getCurrentMonthRecords());
  }

  async ensureFolderForPath(filePath) {
    const parts = normalizePath(filePath).split('/');
    parts.pop();
    if (parts.length === 0) return;

    let current = '';
    for (const part of parts) {
      current = current ? `${current}/${part}` : part;
      const exists = await this.app.vault.adapter.exists(current);
      if (!exists) {
        await this.app.vault.createFolder(current);
      }
    }
  }

  async writeVaultFile(path, content) {
    const filePath = normalizePath(path);
    await this.ensureFolderForPath(filePath);
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (file) {
      await this.app.vault.modify(file, content);
    } else {
      await this.app.vault.create(filePath, content);
    }
  }

  generateDashboardMarkdown() {
    const all = this.getSummary();
    const month = this.getCurrentMonthSummary();
    const records = this.getRecords().slice(0, 30);
    const now = new Date().toLocaleString();

    const row = (name, value) => `| ${name} | ${formatMoney(value)} |`;
    const recordRows = records.length
      ? records.map(r => `| ${r.date || ''}${r.time ? ' ' + r.time : ''} | ${this.getTypeLabel(r.type)} | ${formatMoney(r.amount)} | ${r.category || ''} | ${r.person || ''} | ${r.note || ''} |`).join('\n')
      : `| - | - | - | - | - | ${this.t('noRecords')} |`;

    return `# ${this.t('dashboardTitle')}

> ${this.t('autoGenerated')}${now}

## ${this.t('overview')}

| ${this.t('item')} | ${this.t('value')} |
|---|---:|
${row(this.t('currentAccount'), all.currentAccount)}
${row(this.t('creditCard'), all.creditCard)}
${row(this.t('expense'), all.expense)}
${row(this.t('income'), all.income)}
${row(this.t('loanOut'), all.loanLeft)}

## ${this.t('currentMonth')}

| ${this.t('item')} | ${this.t('value')} |
|---|---:|
${row(this.t('monthlyAccountChange'), month.currentAccount)}
${row(this.t('monthlyCreditChange'), month.creditCard)}
${row(this.t('monthlyExpense'), month.expense)}
${row(this.t('monthlyIncome'), month.income)}
${row(this.t('monthlyLoanLeft'), month.loanLeft)}

## ${this.t('rulesTitle')}

- ${this.t('ruleCurrent')}
- ${this.t('ruleCredit')}
- ${this.t('ruleExpense')}
- ${this.t('ruleLoan')}

## ${this.t('recentRecords')}

| ${this.t('date')} | ${this.t('type')} | ${this.t('amount')} | ${this.t('category')} | ${this.t('person')} | ${this.t('note')} |
|---|---|---:|---|---|---|
${recordRows}
`;
  }

  generateSummaryNoteMarkdown(note) {
    const summary = this.getSummary();
    const title = this.t(note.key);
    const records = this.getRecords().filter(r => note.recordTypes.includes(r.type));
    const now = new Date().toLocaleString();
    const recordRows = records.length
      ? records.map(r => `| ${r.date || ''}${r.time ? ' ' + r.time : ''} | ${this.getTypeLabel(r.type)} | ${formatMoney(r.amount)} | ${r.category || ''} | ${r.person || ''} | ${r.note || ''} |`).join('\n')
      : `| - | - | - | - | - | ${this.t('noRecords')} |`;

    return `# ${title}

> ${this.t('autoGenerated')}${now}

| ${this.t('item')} | ${this.t('value')} |
|---|---:|
| ${title} | ${formatMoney(summary[note.key])} |

## ${this.t('recentRecords')}

| ${this.t('date')} | ${this.t('type')} | ${this.t('amount')} | ${this.t('category')} | ${this.t('person')} | ${this.t('note')} |
|---|---|---:|---|---|---|
${recordRows}
`;
  }

  async updateSummaryNote(note) {
    await this.writeVaultFile(this.getSummaryNotePath(note), this.generateSummaryNoteMarkdown(note));
  }

  async updateAllSummaryNotes() {
    for (const note of SUMMARY_NOTES) {
      await this.updateSummaryNote(note);
    }
  }

  async updateDashboardNote() {
    await this.writeVaultFile(this.getDashboardPath(), this.generateDashboardMarkdown());
  }

  async createOrUpdateCanvas() {
    const canvasGuide = `# ${this.t('canvasGuideTitle')}\n\n1. ${this.t('canvasGuide1')}\n2. ${this.t('canvasGuide2')}\n3. ${this.t('canvasGuide3')}\n\n## ${this.t('typeIntroTitle')}\n\n- ${this.t('guideIncome')}\n- ${this.t('guideExpense')}\n- ${this.t('guideCreditExpense')}\n- ${this.t('guideRepayCredit')}\n- ${this.t('guideLendOut')}\n- ${this.t('guideCollectLoan')}\n- ${this.t('guideAdjust')}`;

    const defaultNodes = [
      {
        id: 'funds-dashboard',
        type: 'file',
        x: 0,
        y: 0,
        width: 620,
        height: 720,
        file: this.getDashboardPath()
      },
      {
        id: 'funds-guide',
        type: 'text',
        x: 660,
        y: 0,
        width: 420,
        height: 340,
        text: canvasGuide
      }
    ];

    const canvasPath = this.getCanvasPath();
    let canvas = { nodes: [], edges: [] };
    if (await this.app.vault.adapter.exists(canvasPath)) {
      try {
        const existing = JSON.parse(await this.app.vault.adapter.read(canvasPath));
        canvas = {
          ...existing,
          nodes: Array.isArray(existing.nodes) ? existing.nodes : [],
          edges: Array.isArray(existing.edges) ? existing.edges : []
        };
      } catch (error) {
        console.error('Personal Funds: failed to read existing canvas, rebuilding default canvas', error);
      }
    }

    const defaultsById = Object.fromEntries(defaultNodes.map(node => [node.id, node]));
    const touched = new Set();
    canvas.nodes = canvas.nodes.map(node => {
      const next = defaultsById[node.id];
      if (!next) return node;
      touched.add(node.id);
      return { ...node, ...next, x: node.x ?? next.x, y: node.y ?? next.y };
    });
    for (const node of defaultNodes) {
      if (!touched.has(node.id)) canvas.nodes.push(node);
    }

    await this.writeVaultFile(canvasPath, JSON.stringify(canvas, null, 2));
  }
};

class PersonalFundsSettingTab extends PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }

  display() {
    const { containerEl } = this;
    containerEl.empty();

    new Setting(containerEl)
      .setName(this.plugin.t('databaseFolderName'))
      .setDesc(this.plugin.t('databaseFolderDesc'))
      .addText(text => {
        text
          .setPlaceholder(DEFAULT_DATA_FOLDER)
          .setValue(this.plugin.getDataFolder())
          .onChange(async value => {
            const folder = normalizePath(value.trim() || DEFAULT_DATA_FOLDER).replace(/^\/+|\/+$/g, '');
            this.plugin.data.settings.dataFolder = folder || DEFAULT_DATA_FOLDER;
            await this.plugin.saveData(this.plugin.data);
            await this.plugin.writeDatabase();
            this.plugin.refreshViews();
          });
      });
  }
}

class FinanceView extends ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }

  getViewType() {
    return VIEW_TYPE_PERSONAL_FUNDS;
  }

  getDisplayText() {
    return this.plugin.t('title');
  }

  getIcon() {
    return 'wallet-cards';
  }

  async onOpen() {
    this.containerEl.addClass('milin-finance-shell');
    this.containerEl.addClass('personal-funds-view-shell');
    this.render();
  }

  async onClose() {
    this.contentEl.empty();
    this.containerEl.removeClass('milin-finance-shell');
    this.containerEl.removeClass('personal-funds-view-shell');
  }

  render() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass('milin-finance-modal');
    contentEl.addClass('milin-finance-tab');

    const header = contentEl.createDiv({ cls: 'milin-finance-header' });
    header.createEl('h2', { text: this.plugin.t('title') });

    const headerActions = header.createDiv({ cls: 'milin-finance-header-actions' });
    const langBtn = headerActions.createEl('button', {
      cls: 'milin-finance-lang-toggle',
      text: this.plugin.t('languageSwitch'),
      attr: { title: this.plugin.t('switchTitle') }
    });
    langBtn.onclick = async () => {
      await this.plugin.toggleLanguage();
      new Notice(this.plugin.t('languageName'));
      this.render();
    };

    this.renderSummary(contentEl);
    this.renderForm(contentEl);
    this.renderCanvasActions(contentEl);
    this.renderRecords(contentEl);
  }

  renderSummary(root) {
    const s = this.plugin.getSummary();
    const box = root.createDiv({ cls: 'milin-finance-summary' });

    this.summaryCard(box, this.plugin.t('currentAccount'), s.currentAccount, 'wallet', 'account', SUMMARY_NOTES[0], this.plugin.t('summaryAfterCredit', s.creditCard));
    this.summaryCard(box, this.plugin.t('creditCard'), s.creditCard, 'credit-card', 'credit', SUMMARY_NOTES[1]);
    this.summaryCard(box, this.plugin.t('expense'), s.expense, 'trending-down', 'expense', SUMMARY_NOTES[2]);
    this.summaryCard(box, this.plugin.t('income'), s.income, 'trending-up', 'income', SUMMARY_NOTES[3]);
    this.summaryCard(box, this.plugin.t('loanOut'), s.loanLeft, 'user-round-plus', 'loan', SUMMARY_NOTES[4]);
  }

  summaryCard(root, title, value, iconName, tone, note, subValue) {
    const text = formatMoney(value);
    const card = root.createDiv({ cls: `milin-finance-card milin-finance-card--${tone}` });
    card.setAttr('role', 'button');
    card.setAttr('tabindex', '0');
    card.setAttr('aria-label', `${title}: ${text}`);
    card.setAttr('title', this.plugin.getSummaryNotePath(note));
    card.onclick = () => this.plugin.openSummaryNote(note);
    card.onkeydown = event => {
      if (event.key === 'Enter' || event.key === ' ') {
        event.preventDefault();
        this.plugin.openSummaryNote(note);
      }
    };

    const iconWrap = card.createDiv({ cls: 'milin-finance-card-icon' });
    setIcon(iconWrap, iconName);

    card.createDiv({ cls: 'milin-finance-card-title', text: title });
    const valueEl = card.createDiv({ cls: 'milin-finance-card-value', text });
    valueEl.style.setProperty('--milin-value-size', valueFontSize(text));
    if (subValue) {
      card.createDiv({ cls: 'milin-finance-card-subvalue', text: subValue });
    }
  }

  renderForm(root) {
    const form = root.createDiv({ cls: 'milin-finance-form' });

    const typeSelect = form.createEl('select', { cls: 'milin-finance-control milin-finance-type' });
    for (const t of TYPES) {
      const opt = typeSelect.createEl('option', { text: t.labels[this.plugin.getLanguage()] || t.labels.zh });
      opt.value = t.id;
    }

    const amountInput = form.createEl('input', {
      cls: 'milin-finance-control milin-finance-amount',
      attr: { type: 'number', placeholder: this.plugin.t('amount') }
    });
    amountInput.inputMode = 'decimal';

    const categorySelect = form.createEl('select', { cls: 'milin-finance-control milin-finance-category' });
    for (const c of this.plugin.getCategories()) {
      const opt = categorySelect.createEl('option', { text: c });
      opt.value = c;
    }

    const personInput = form.createEl('input', {
      cls: 'milin-finance-control milin-finance-person',
      attr: { type: 'text', placeholder: this.plugin.t('personPlaceholder') }
    });

    const noteInput = form.createEl('input', {
      cls: 'milin-finance-control milin-finance-note',
      attr: { type: 'text', placeholder: this.plugin.t('notePlaceholder') }
    });

    const saveBtn = form.createEl('button', { cls: 'milin-finance-save', text: this.plugin.t('save') });

    saveBtn.onclick = async () => {
      const amount = Number(amountInput.value);
      if (!amount || amount <= 0) {
        new Notice(this.plugin.t('amountNotice'));
        amountInput.focus();
        return;
      }

      const { date, time } = localDateParts();
      await this.plugin.addRecord({
        id: `${Date.now()}_${Math.random().toString(16).slice(2)}`,
        date,
        time,
        type: typeSelect.value,
        amount,
        category: categorySelect.value,
        person: personInput.value.trim(),
        note: noteInput.value.trim()
      });

      new Notice(this.plugin.t('savedNotice'));
      this.render();
    };
  }

  renderCanvasActions(root) {
    const box = root.createDiv({ cls: 'milin-finance-actions' });

    const dashboardBtn = box.createEl('button', { cls: 'milin-finance-action', text: this.plugin.t('updateDashboard') });
    const docIcon = dashboardBtn.createSpan({ cls: 'milin-finance-action-icon' });
    setIcon(docIcon, 'file-text');
    dashboardBtn.prepend(docIcon);
    dashboardBtn.onclick = async () => {
      await this.plugin.updateDashboardNote();
      new Notice(this.plugin.t('dashboardUpdatedNotice'));
    };

    const canvasBtn = box.createEl('button', { cls: 'milin-finance-action', text: this.plugin.t('createCanvas') });
    const canvasIcon = canvasBtn.createSpan({ cls: 'milin-finance-action-icon' });
    setIcon(canvasIcon, 'layout-grid');
    canvasBtn.prepend(canvasIcon);
    canvasBtn.onclick = async () => {
      await this.plugin.updateDashboardNote();
      await this.plugin.createOrUpdateCanvas();
      new Notice(this.plugin.t('canvasUpdatedNotice'));
    };

    const readBtn = box.createEl('button', { cls: 'milin-finance-action', text: this.plugin.t('readDatabase') });
    const readIcon = readBtn.createSpan({ cls: 'milin-finance-action-icon' });
    setIcon(readIcon, 'database');
    readBtn.prepend(readIcon);
    readBtn.onclick = async () => {
      const loaded = await this.plugin.readDatabase();
      if (loaded) {
        new Notice(this.plugin.t('databaseReadNotice'));
        this.render();
      }
    };
  }

  renderRecords(root) {
    const records = this.plugin.getRecords().slice(0, 30);
    const top = root.createDiv({ cls: 'milin-finance-record-head' });
    top.createEl('h3', { text: this.plugin.t('recentRecords') });
    const count = top.createDiv({ cls: 'milin-finance-record-count' });
    setIcon(count, 'clock-3');
    count.createSpan({ text: this.plugin.t('recordCount', records.length) });

    const list = root.createDiv({ cls: 'milin-finance-records' });

    if (records.length === 0) {
      list.createDiv({ cls: 'milin-finance-empty', text: this.plugin.t('noRecords') });
      return;
    }

    for (const r of records) {
      const row = list.createDiv({ cls: `milin-finance-record-row milin-finance-record-row--${this.plugin.getTypeTone(r.type)}` });
      const typeLabel = this.plugin.getTypeLabel(r.type);
      const tone = this.plugin.getTypeTone(r.type);

      const icon = row.createDiv({ cls: 'milin-finance-record-icon' });
      setIcon(icon, this.recordIcon(r.type));

      const dt = row.createDiv({ cls: 'milin-finance-record-date', text: `${r.date || ''}${r.time ? ' ' + r.time : ''}` });
      dt.setAttr('title', `${r.date || ''}${r.time ? ' ' + r.time : ''}`);

      row.createDiv({ cls: `milin-finance-badge milin-finance-badge--${tone}`, text: typeLabel });

      row.createDiv({ cls: `milin-finance-record-amount milin-finance-record-amount--${tone}`, text: this.recordAmountText(r) });

      const category = row.createDiv({ cls: 'milin-finance-record-meta' });
      setIcon(category, 'utensils');
      category.createSpan({ text: r.category || this.plugin.t('uncategorized') });

      const person = row.createDiv({ cls: 'milin-finance-record-meta' });
      setIcon(person, 'user-round');
      person.createSpan({ text: r.person || this.plugin.t('self') });

      const note = row.createDiv({ cls: 'milin-finance-record-note' });
      setIcon(note, 'message-square');
      note.createSpan({ text: r.note || this.plugin.t('emptyNote') });

      const del = row.createEl('button', { cls: 'milin-finance-delete', attr: { 'aria-label': this.plugin.t('delete') } });
      setIcon(del, 'trash-2');
      del.onclick = async () => {
        await this.plugin.deleteRecord(r.id);
        new Notice(this.plugin.t('deletedNotice'));
        this.render();
      };
    }

    const tip = root.createDiv({ cls: 'milin-finance-tip' });
    setIcon(tip, 'info');
    tip.createSpan({ text: this.plugin.t('tip') });
  }

  recordIcon(type) {
    if (type === 'income' || type === 'collect_loan') return 'arrow-up';
    if (type === 'expense' || type === 'credit_expense' || type === 'repay_credit' || type === 'lend_out') return 'arrow-down';
    return 'equal';
  }

  recordAmountText(record) {
    const amount = Number(record.amount || 0);
    if (record.type === 'income' || record.type === 'collect_loan' || record.type === 'account_adjust') {
      return signedMoney(amount);
    }
    return signedMoney(-amount);
  }
}
