const { Plugin, ItemView, Modal, Notice, PluginSettingTab, Setting, normalizePath, setIcon } = require('obsidian');

const VIEW_TYPE_PERSONAL_FUNDS = 'personal-funds-view';
const DEFAULT_DATA_FOLDER = 'Personal_funds';
// Keep the primary database in Markdown.  Many vault sync/backup services only
// include notes, while they skip .json files (and everything in .obsidian).
const DATABASE_FILE_NAME = 'records.md';
const LEGACY_DATABASE_FILE_NAME = 'records.json';
const LEGACY_PLUGIN_DATA_PATH = '.obsidian/plugins/milin-simple-finance/data.json';

const SUMMARY_NOTES = [
  { key: 'currentAccount', slug: 'current-account', type: 'account', recordTypes: ['income', 'expense', 'repay_credit', 'lend_out', 'collect_loan', 'account_adjust', 'borrow_in', 'repay_debt'] },
  { key: 'creditCard', slug: 'credit-card', type: 'credit', recordTypes: ['credit_expense', 'repay_credit'] },
  { key: 'expense', slug: 'expense', type: 'expense', recordTypes: ['expense', 'credit_expense'] },
  { key: 'income', slug: 'income', type: 'income', recordTypes: ['income'] },
  { key: 'loanOut', slug: 'lending', type: 'loan', recordTypes: ['lend_out', 'collect_loan'] }
];

const TYPES = [
  { id: 'income', labels: { zh: '收入', en: 'Income' }, tone: 'income' },
  { id: 'expense', labels: { zh: '支出', en: 'Expense' }, tone: 'expense' },
  { id: 'credit_expense', labels: { zh: '信用卡支出', en: 'Credit expense' }, tone: 'credit' },
  { id: 'repay_credit', labels: { zh: '还信用卡', en: 'Repay credit card' }, tone: 'credit' },
  { id: 'lend_out', labels: { zh: '借出', en: 'Lend out' }, tone: 'loan' },
  { id: 'collect_loan', labels: { zh: '收回借出', en: 'Collect loan' }, tone: 'loan' },
  { id: 'account_adjust', labels: { zh: '当前账户调整', en: 'Account adjustment' }, tone: 'neutral' }
];

const TYPE_MAP = Object.fromEntries(TYPES.map(t => [t.id, t]));

const DEFAULT_CATEGORIES = {
  zh: ['吃饭', '交通', '设备/元器件', '学习', '接单', '工资', '信用卡', '借出', '初始余额', '人情', '其他'],
  en: ['Food', 'Transport', 'Devices/Parts', 'Learning', 'Freelance', 'Salary', 'Credit card', 'Lending', 'Initial balance', 'Social', 'Other']
};

const I18N = {
  zh: {
    title: 'Personal Funds',
    languageName: '中文',
    languageSwitch: 'EN',
    switchTitle: 'Switch to English',
    currentAccount: '当前账户',
    creditCard: '信用卡',
    expense: '支出',
    expectedExpense: '预计支出',
    expectedExpenseDescription: '填写未来已确定、但尚未记账的支出金额。它不会改变当前账户余额。',
    expectedExpensePrompt: '设置预计支出',
    expectedExpenseSaved: '预计支出已保存',
    addRecord: '记一笔',
    viewAll: '查看全部',
    navigation: '导航',
    fixedExpense: '固定支出',
    accountManagement: '账户管理',
    settings: '设置',
    fixedExpenseAdd: '添加固定支出',
    fixedExpenseName: '名称',
    fixedExpenseNamePlaceholder: '例如：房租、订阅',
    fixedExpenseEmpty: '还没有固定支出条目',
    fixedExpenseSaved: '固定支出已保存',
    allRecords: '全部类型',
    allCategories: '全部分类',
    resetFilter: '重置筛选',
    availableBalance: '可用余额',
    afterExpectedExpense: '扣除预计支出后',
    expectedTotalExpense: '含预计支出的总额',
    accountOverview: '账户概览',
    accountList: '资金明细',
    balanceTrend: '余额趋势',
    recentSevenDays: '近 7 天',
    creditDue: '信用卡待还',
    lendingOutstanding: '借出未收',
    viewDetails: '查看详情',
    currentMonthTotal: '本月金额',
    monthlyTrend: '本月趋势',
    noTrendData: '暂无足够的趋势数据',
    income: '收入',
    loanOut: '借出',
    amount: '金额',
    personPlaceholder: '对象：谁',
    notePlaceholder: '备注，可不填',
    save: '保存',
    updateDashboard: 'MD',
    createCanvas: 'Canvas',
    readDatabase: 'Read',
    recentRecords: '最近记录',
    recordCount: count => `共 ${count} 条记录`,
    noRecords: '还没有记录。',
    uncategorized: '未分类',
    self: '自己',
    emptyNote: '-',
    delete: '删除',
    amountNotice: '请输入大于 0 的金额',
    savedNotice: '已保存，并已更新资金看板',
    deletedNotice: '已删除，并已更新资金看板',
    dashboardUpdatedNotice: '资金看板.md 已更新',
    canvasUpdatedNotice: '资金看板.canvas 已创建/更新',
    databaseReadNotice: '已从 Markdown 数据库读取记录',
    databaseSavedNotice: 'Markdown 数据库已保存',
    databaseMissingNotice: '还没有 Markdown 数据库文件，会在下次保存记录时创建',
    tip: '金额位数较多时，顶部数字会自动缩小，保证 5 个卡片稳定显示。',
    dashboardTitle: '资金看板',
    autoGenerated: '由 Personal Funds 自动生成。更新时间：',
    databaseFolderName: '数据文件夹',
    databaseFolderDesc: '记录会保存为可同步的 Markdown 文件；资金看板、Canvas 和单项记录也会保存在这个文件夹。',
    summaryAfterCredit: value => `扣除信用卡提醒：${formatMoney(value)}`,
    overview: '总览',
    currentMonth: '本月',
    item: '项目',
    value: '金额',
    monthlyAccountChange: '本月当前账户变化',
    monthlyCreditChange: '本月信用卡新增/减少',
    monthlyExpense: '本月支出',
    monthlyIncome: '本月收入',
    monthlyLoanLeft: '本月借出未收回',
    rulesTitle: '口径说明',
    ruleCurrent: '当前账户 = 收入 - 支出 - 还信用卡 - 借出 + 收回借出 + 当前账户调整。',
    ruleCredit: '信用卡 = 信用卡支出 - 还信用卡。',
    ruleExpense: '支出 = 现金支出 + 信用卡支出。',
    ruleLoan: '借出 = 借出 - 收回借出。',
    date: '日期',
    type: '类型',
    category: '分类',
    person: '对象',
    note: '备注',
    canvasGuideTitle: '使用方法',
    canvasGuide1: '点击左侧钱包图标记账',
    canvasGuide2: '保存后自动更新“资金看板.md”',
    canvasGuide3: '在 Canvas 中查看汇总',
    typeIntroTitle: '类型',
    guideIncome: '收入：钱进入当前账户',
    guideExpense: '支出：当前账户直接花钱',
    guideCreditExpense: '信用卡支出：信用卡欠款增加',
    guideRepayCredit: '还信用卡：当前账户减少，信用卡欠款减少',
    guideLendOut: '借出：别人欠你钱',
    guideCollectLoan: '收回借出：别人还你钱',
    guideAdjust: '当前账户调整：设置初始余额或修正余额',
    legacyBorrowIn: '负债/借入',
    legacyRepayDebt: '负债/还债'
  },
  en: {
    title: 'Personal Funds',
    languageName: 'English',
    languageSwitch: '中文',
    switchTitle: '切换到中文',
    currentAccount: 'Current account',
    creditCard: 'Credit card',
    expense: 'Expense',
    expectedExpense: 'Expected expense',
    expectedExpenseDescription: 'Enter confirmed future spending that has not been recorded yet. It does not change the current account balance.',
    expectedExpensePrompt: 'Set expected expense',
    expectedExpenseSaved: 'Expected expense saved',
    addRecord: 'Add record',
    viewAll: 'View all',
    navigation: 'Navigation',
    fixedExpense: 'Planned expense',
    accountManagement: 'Accounts',
    settings: 'Settings',
    fixedExpenseAdd: 'Add planned expense',
    fixedExpenseName: 'Name',
    fixedExpenseNamePlaceholder: 'For example: Rent or subscription',
    fixedExpenseEmpty: 'No planned expenses yet',
    fixedExpenseSaved: 'Planned expense saved',
    allRecords: 'All types',
    allCategories: 'All categories',
    resetFilter: 'Reset filters',
    availableBalance: 'Available balance',
    afterExpectedExpense: 'After expected expense',
    expectedTotalExpense: 'Including expected expense',
    accountOverview: 'Account overview',
    accountList: 'Funds breakdown',
    balanceTrend: 'Balance trend',
    recentSevenDays: 'Last 7 days',
    creditDue: 'Credit due',
    lendingOutstanding: 'Lending outstanding',
    viewDetails: 'View details',
    currentMonthTotal: 'This month',
    monthlyTrend: 'Monthly trend',
    noTrendData: 'Not enough data for a trend yet',
    income: 'Income',
    loanOut: 'Lending',
    amount: 'Amount',
    personPlaceholder: 'Person',
    notePlaceholder: 'Note, optional',
    save: 'Save',
    updateDashboard: 'MD',
    createCanvas: 'Canvas',
    readDatabase: 'Read',
    recentRecords: 'Recent records',
    recordCount: count => `${count} record${count === 1 ? '' : 's'}`,
    noRecords: 'No records yet.',
    uncategorized: 'Uncategorized',
    self: 'Self',
    emptyNote: '-',
    delete: 'Delete',
    amountNotice: 'Enter an amount greater than 0',
    savedNotice: 'Saved and dashboard updated',
    deletedNotice: 'Deleted and dashboard updated',
    dashboardUpdatedNotice: 'Funds dashboard.md updated',
    canvasUpdatedNotice: 'Funds dashboard canvas created/updated',
    databaseReadNotice: 'Records loaded from the Markdown database',
    databaseSavedNotice: 'Markdown database saved',
    databaseMissingNotice: 'No Markdown database file yet. It will be created the next time you save a record.',
    tip: 'Longer numbers automatically shrink so all 5 summary cards stay stable.',
    dashboardTitle: 'Funds dashboard',
    autoGenerated: 'Auto-generated by Personal Funds. Updated at: ',
    databaseFolderName: 'Data folder',
    databaseFolderDesc: 'Records are saved in a sync-friendly Markdown file; the dashboard, Canvas, and summary notes are saved here too.',
    summaryAfterCredit: value => `After credit reminder: ${formatMoney(value)}`,
    overview: 'Overview',
    currentMonth: 'This month',
    item: 'Item',
    value: 'Amount',
    monthlyAccountChange: 'Monthly account change',
    monthlyCreditChange: 'Monthly credit card change',
    monthlyExpense: 'Monthly expense',
    monthlyIncome: 'Monthly income',
    monthlyLoanLeft: 'Monthly lending not collected',
    rulesTitle: 'Calculation rules',
    ruleCurrent: 'Current account = income - expense - credit card repayments - lending + collected loans + account adjustments.',
    ruleCredit: 'Credit card = credit card expenses - credit card repayments.',
    ruleExpense: 'Expense = cash expense + credit card expense.',
    ruleLoan: 'Lending = lend out - collect loan.',
    date: 'Date',
    type: 'Type',
    category: 'Category',
    person: 'Person',
    note: 'Note',
    canvasGuideTitle: 'How to use',
    canvasGuide1: 'Click the wallet icon on the left to add a record',
    canvasGuide2: 'The funds dashboard.md note updates automatically after saving',
    canvasGuide3: 'View the summary in Canvas',
    typeIntroTitle: 'Types',
    guideIncome: 'Income: money enters your current account',
    guideExpense: 'Expense: spend directly from your current account',
    guideCreditExpense: 'Credit expense: credit card debt increases',
    guideRepayCredit: 'Repay credit card: current account decreases and card debt decreases',
    guideLendOut: 'Lend out: someone owes you money',
    guideCollectLoan: 'Collect loan: someone repays you',
    guideAdjust: 'Account adjustment: set initial balance or correct balance',
    legacyBorrowIn: 'Borrow in',
    legacyRepayDebt: 'Repay debt'
  }
};

const DASHBOARD_FILE_NAME = 'Funds dashboard.md';
const CANVAS_FILE_NAME = 'Funds dashboard.canvas';

function pad2(n) {
  return String(n).padStart(2, '0');
}

function localDateParts(date = new Date()) {
  const yyyy = date.getFullYear();
  const mm = pad2(date.getMonth() + 1);
  const dd = pad2(date.getDate());
  const hh = pad2(date.getHours());
  const mi = pad2(date.getMinutes());
  return { date: `${yyyy}-${mm}-${dd}`, time: `${hh}:${mi}` };
}

function formatMoney(value) {
  const num = Number(value || 0);
  return num.toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2
  });
}

function signedMoney(value, positivePrefix = '+') {
  const num = Number(value || 0);
  const abs = Math.abs(num);
  const sign = num > 0 ? positivePrefix : num < 0 ? '-' : '';
  return `${sign}${formatMoney(abs)}`;
}

function valueFontSize(text) {
  const len = String(text).length;
  if (len <= 4) return '30px';
  if (len <= 7) return '28px';
  if (len <= 9) return '25px';
  if (len <= 12) return '22px';
  return '19px';
}

module.exports = class PersonalFundsPlugin extends Plugin {
  async onload() {
    this.data = await this.loadData();
    if (!this.data || typeof this.data !== 'object') {
      this.data = { records: [], settings: { language: 'zh' } };
    }
    if (!Array.isArray(this.data.records)) {
      this.data.records = [];
    }
    if (!this.data.settings || typeof this.data.settings !== 'object') {
      this.data.settings = {};
    }
    if (!['zh', 'en'].includes(this.data.settings.language)) {
      this.data.settings.language = 'zh';
    }
    if (!this.data.settings.dataFolder || typeof this.data.settings.dataFolder !== 'string') {
      this.data.settings.dataFolder = DEFAULT_DATA_FOLDER;
    }
    if (!Number.isFinite(Number(this.data.settings.expectedExpense)) || Number(this.data.settings.expectedExpense) < 0) {
      this.data.settings.expectedExpense = 0;
    }
    if (!Array.isArray(this.data.settings.fixedExpenses)) {
      this.data.settings.fixedExpenses = [];
    }
    await this.loadDatabaseOnStartup();
    await this.saveData(this.data);
    this.addSettingTab(new PersonalFundsSettingTab(this.app, this));

    this.registerView(
      VIEW_TYPE_PERSONAL_FUNDS,
      leaf => new FinanceView(leaf, this)
    );

    this.addRibbonIcon('wallet-cards', this.t('title'), () => {
      this.openFinanceView();
    });

    this.addCommand({
      id: 'open-personal-funds',
      name: 'Open personal funds',
      callback: () => this.openFinanceView()
    });

    this.addCommand({
      id: 'update-funds-dashboard',
      name: 'Update funds dashboard markdown',
      callback: async () => {
        await this.updateDashboardNote();
        new Notice(this.t('dashboardUpdatedNotice'));
      }
    });

    this.addCommand({
      id: 'create-funds-canvas',
      name: 'Create or update funds canvas',
      callback: async () => {
        await this.updateDashboardNote();
        await this.createOrUpdateCanvas();
        new Notice(this.t('canvasUpdatedNotice'));
      }
    });

    this.addCommand({
      id: 'read-funds-database',
      name: 'Read funds Markdown database',
      callback: async () => {
        const loaded = await this.readDatabase();
        if (loaded) {
          new Notice(this.t('databaseReadNotice'));
          this.refreshViews();
        }
      }
    });
  }

  async openFinanceView() {
    let leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_PERSONAL_FUNDS)[0];
    if (!leaf) {
      leaf = this.app.workspace.getLeaf('tab');
      await leaf.setViewState({
        type: VIEW_TYPE_PERSONAL_FUNDS,
        active: true
      });
    }
    this.app.workspace.revealLeaf(leaf);
  }

  getDataFolder() {
    const folder = String(this.data?.settings?.dataFolder || DEFAULT_DATA_FOLDER).trim();
    return normalizePath(folder || DEFAULT_DATA_FOLDER).replace(/^\/+|\/+$/g, '');
  }

  getVaultPath(fileName) {
    return normalizePath(`${this.getDataFolder()}/${fileName}`);
  }

  getDatabasePath() {
    return this.getVaultPath(DATABASE_FILE_NAME);
  }

  getLegacyDatabasePath() {
    return this.getVaultPath(LEGACY_DATABASE_FILE_NAME);
  }

  getDashboardPath() {
    return this.getVaultPath(DASHBOARD_FILE_NAME);
  }

  getCanvasPath() {
    return this.getVaultPath(CANVAS_FILE_NAME);
  }

  getSummaryNotePath(note) {
    return this.getVaultPath(`Summary/${note.slug}.md`);
  }

  async loadDatabaseOnStartup() {
    try {
      const loaded = await this.readDatabase(false);
      if (loaded) return;
    } catch (error) {
      console.error('Personal Funds: failed to read database on startup', error);
      new Notice('Personal Funds database read failed. Check records.md.');
    }

    const migrated = await this.tryReadLegacyPluginData();
    if (migrated) {
      await this.writeDatabase();
      return;
    }

    if (this.getRecords().length > 0) {
      await this.writeDatabase();
    }
  }

  async readDatabase(showMissingNotice = true) {
    const path = this.getDatabasePath();
    let raw;
    let sourcePath = path;
    if (await this.app.vault.adapter.exists(path)) {
      raw = await this.app.vault.adapter.read(path);
    } else {
      // One-time compatibility import for vaults created by versions that used
      // records.json.  The next write migrates the data to records.md.
      const legacyPath = this.getLegacyDatabasePath();
      if (await this.app.vault.adapter.exists(legacyPath)) {
        raw = await this.app.vault.adapter.read(legacyPath);
        sourcePath = legacyPath;
      } else {
        // Plugin settings live in .obsidian and may not be restored on a new
        // computer.  Find a valid Markdown database anywhere in the vault so
        // a custom data folder can recover without manual configuration.
        const discoveredPath = await this.findDatabasePath();
        if (!discoveredPath) {
          if (showMissingNotice) new Notice(this.t('databaseMissingNotice'));
          return false;
        }
        raw = await this.app.vault.adapter.read(discoveredPath);
        sourcePath = discoveredPath;
      }
    }

    const parsed = this.parseDatabase(raw, sourcePath);
    const records = Array.isArray(parsed) ? parsed : parsed.records;
    if (!Array.isArray(records)) {
      throw new Error(`Invalid Personal Funds database: ${path}`);
    }

    const sourceFolder = normalizePath(sourcePath).split('/').slice(0, -1).join('/');
    if (sourceFolder) this.data.settings.dataFolder = sourceFolder;
    this.data.records = records;
    if (parsed.settings && typeof parsed.settings === 'object') {
      this.data.settings = { ...this.data.settings, ...parsed.settings, dataFolder: this.getDataFolder() };
    }
    await this.saveData(this.data);
    if (sourcePath !== path) await this.writeDatabase();
    return true;
  }

  async findDatabasePath() {
    const matches = [];
    for (const file of this.app.vault.getFiles()) {
      if (file.path !== DATABASE_FILE_NAME && !file.path.endsWith(`/${DATABASE_FILE_NAME}`)) continue;
      try {
        const parsed = this.parseDatabase(await this.app.vault.read(file), file.path);
        const records = Array.isArray(parsed) ? parsed : parsed.records;
        if (!Array.isArray(records)) continue;
        const updatedAt = Date.parse(parsed.updatedAt || '') || 0;
        matches.push({ path: file.path, updatedAt });
      } catch (error) {
        // A note named records.md is not necessarily a Personal Funds database.
      }
    }
    matches.sort((a, b) => b.updatedAt - a.updatedAt || a.path.localeCompare(b.path));
    return matches[0]?.path || null;
  }

  parseDatabase(raw, path) {
    const content = String(raw).trim();
    // records.md stores the portable payload in a fenced JSON block.  The
    // fallback keeps manually restored JSON files and old versions readable.
    const fenced = content.match(/```(?:json)?\s*\r?\n([\s\S]*?)\r?\n```/i);
    const payload = fenced ? fenced[1].trim() : content;
    try {
      return JSON.parse(payload);
    } catch (error) {
      throw new Error(`Invalid Personal Funds database: ${path}`);
    }
  }

  async tryReadLegacyPluginData() {
    const exists = await this.app.vault.adapter.exists(LEGACY_PLUGIN_DATA_PATH);
    if (!exists) return false;

    try {
      const parsed = JSON.parse(await this.app.vault.adapter.read(LEGACY_PLUGIN_DATA_PATH));
      if (!Array.isArray(parsed.records) || parsed.records.length === 0) return false;
      this.data.records = parsed.records;
      this.data.settings = { ...this.data.settings, ...(parsed.settings || {}) };
      if (!this.data.settings.dataFolder) this.data.settings.dataFolder = DEFAULT_DATA_FOLDER;
      return true;
    } catch (error) {
      console.error('Personal Funds: failed to read legacy plugin data', error);
      return false;
    }
  }

  async writeDatabase() {
    const payload = {
      version: 1,
      updatedAt: new Date().toISOString(),
      settings: {
        language: this.getLanguage(),
        expectedExpense: this.getManualExpectedExpense(),
        fixedExpenses: this.getFixedExpenses()
      },
      records: this.getRecords()
    };
    const content = [
      '# Personal Funds records',
      '',
      '> This is the primary data file for Personal Funds. Keep it in your vault so normal note sync and backups include your records.',
      '',
      '```json',
      JSON.stringify(payload, null, 2),
      '```',
      ''
    ].join('\n');
    await this.writeVaultFile(this.getDatabasePath(), content);
  }

  refreshViews() {
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_PERSONAL_FUNDS)) {
      leaf.view?.render?.();
    }
  }

  async openMarkdownSource(path) {
    const file = this.app.vault.getAbstractFileByPath(normalizePath(path));
    if (!file) {
      new Notice(this.t('dashboardUpdatedNotice'));
      return;
    }

    const leaf = this.app.workspace.getLeaf('tab');
    await leaf.openFile(file, {
      active: true,
      state: { mode: 'source' }
    });
  }

  async openDashboardNote() {
    await this.updateDashboardNote();
    await this.openMarkdownSource(this.getDashboardPath());
  }

  async openSummaryNote(note) {
    await this.updateSummaryNote(note);
    await this.openMarkdownSource(this.getSummaryNotePath(note));
  }

  getLanguage() {
    return this.data?.settings?.language || 'zh';
  }

  getManualExpectedExpense() {
    return Math.max(0, Number(this.data?.settings?.expectedExpense) || 0);
  }

  getFixedExpenses() {
    return Array.isArray(this.data?.settings?.fixedExpenses) ? this.data.settings.fixedExpenses : [];
  }

  getExpectedExpense() {
    return this.getManualExpectedExpense() + this.getFixedExpenses().reduce((total, item) => total + Math.max(0, Number(item.amount) || 0), 0);
  }

  async setExpectedExpense(amount) {
    this.data.settings.expectedExpense = Math.max(0, Number(amount) || 0);
    await this.saveData(this.data);
    await this.writeDatabase();
    await this.updateDashboardNote();
  }

  async addFixedExpense(item) {
    this.data.settings.fixedExpenses.unshift(item);
    await this.saveData(this.data);
    await this.writeDatabase();
    await this.updateDashboardNote();
  }

  async deleteFixedExpense(id) {
    this.data.settings.fixedExpenses = this.getFixedExpenses().filter(item => item.id !== id);
    await this.saveData(this.data);
    await this.writeDatabase();
    await this.updateDashboardNote();
  }

  t(key, ...args) {
    const lang = this.getLanguage();
    const value = I18N[lang]?.[key] ?? I18N.zh[key] ?? key;
    return typeof value === 'function' ? value(...args) : value;
  }

  async toggleLanguage() {
    this.data.settings.language = this.getLanguage() === 'zh' ? 'en' : 'zh';
    await this.saveData(this.data);
    await this.writeDatabase();
  }

  getCategories() {
    return DEFAULT_CATEGORIES[this.getLanguage()] || DEFAULT_CATEGORIES.zh;
  }

  async addRecord(record) {
    this.data.records.unshift(record);
    await this.saveData(this.data);
    await this.writeDatabase();
    await this.updateDashboardNote();
  }

  async deleteRecord(id) {
    this.data.records = this.data.records.filter(r => r.id !== id);
    await this.saveData(this.data);
    await this.writeDatabase();
    await this.updateDashboardNote();
  }

  getRecords() {
    return this.data.records || [];
  }

  getTypeLabel(type) {
    const lang = this.getLanguage();
    return TYPE_MAP[type]?.labels?.[lang] || TYPE_MAP[type]?.labels?.zh || this.getLegacyTypeLabel(type);
  }

  getTypeTone(type) {
    return TYPE_MAP[type]?.tone || 'neutral';
  }

  getLegacyTypeLabel(type) {
    const legacy = {
      borrow_in: this.t('legacyBorrowIn'),
      repay_debt: this.t('legacyRepayDebt'),
      lend_out: this.getTypeLabel('lend_out'),
      collect_loan: this.getTypeLabel('collect_loan')
    };
    return legacy[type] || type;
  }

  emptySummary() {
    return {
      currentAccount: 0,
      creditCard: 0,
      expense: 0,
      income: 0,
      loanLeft: 0,
      collectLoan: 0,
      accountAdjust: 0
    };
  }

  applyRecordToSummary(summary, record) {
    const amount = Number(record.amount) || 0;

    switch (record.type) {
      case 'income':
        summary.income += amount;
        summary.currentAccount += amount;
        break;

      case 'expense':
        summary.expense += amount;
        summary.currentAccount -= amount;
        break;

      case 'credit_expense':
        summary.expense += amount;
        summary.creditCard += amount;
        break;

      case 'repay_credit':
        summary.currentAccount -= amount;
        summary.creditCard -= amount;
        break;

      case 'lend_out':
        summary.loanLeft += amount;
        summary.currentAccount -= amount;
        break;

      case 'collect_loan':
        summary.collectLoan += amount;
        summary.loanLeft -= amount;
        summary.currentAccount += amount;
        break;

      case 'account_adjust':
        summary.accountAdjust += amount;
        summary.currentAccount += amount;
        break;

      case 'borrow_in':
        summary.currentAccount += amount;
        break;

      case 'repay_debt':
        summary.currentAccount -= amount;
        break;

      default:
        break;
    }
  }

  getSummary(records = this.getRecords()) {
    const summary = this.emptySummary();
    for (const r of records) {
      this.applyRecordToSummary(summary, r);
    }
    return summary;
  }

  getCurrentMonthRecords() {
    const { date } = localDateParts();
    const ym = date.slice(0, 7);
    return this.getRecords().filter(r => String(r.date || '').startsWith(ym));
  }

  getCurrentMonthSummary() {
    return this.getSummary(this.getCurrentMonthRecords());
  }

  getBalanceTrend(days = 7) {
    const dateForOffset = offset => {
      const value = new Date();
      value.setHours(0, 0, 0, 0);
      value.setDate(value.getDate() + offset);
      const month = String(value.getMonth() + 1).padStart(2, '0');
      const date = String(value.getDate()).padStart(2, '0');
      return `${value.getFullYear()}-${month}-${date}`;
    };
    const dates = Array.from({ length: days }, (_, index) => dateForOffset(index - days + 1));
    const firstDate = dates[0];
    const balanceBeforePeriod = this.getSummary(this.getRecords().filter(record => String(record.date || '') < firstDate)).currentAccount;
    let balance = balanceBeforePeriod;
    return dates.map(date => {
      // Apply records with the normal summary rules without mutating stored data.
      const summary = { currentAccount: balance, creditCard: 0, expense: 0, income: 0, loanLeft: 0, collectLoan: 0, accountAdjust: 0 };
      for (const record of this.getRecords()) {
        if (record.date === date) this.applyRecordToSummary(summary, record);
      }
      balance = summary.currentAccount;
      return { date, value: balance };
    });
  }

  getMonthlyFlowTrend(days = 7) {
    const dateForOffset = offset => {
      const value = new Date();
      value.setHours(0, 0, 0, 0);
      value.setDate(value.getDate() + offset);
      const month = String(value.getMonth() + 1).padStart(2, '0');
      const date = String(value.getDate()).padStart(2, '0');
      return `${value.getFullYear()}-${month}-${date}`;
    };
    const dates = Array.from({ length: days }, (_, index) => dateForOffset(index - days + 1));
    return dates.map(date => {
      let income = 0;
      let expense = 0;
      for (const record of this.getRecords()) {
        if (record.date !== date) continue;
        const amount = Number(record.amount) || 0;
        if (record.type === 'income' || record.type === 'collect_loan') income += amount;
        if (record.type === 'expense' || record.type === 'credit_expense' || record.type === 'repay_credit' || record.type === 'lend_out') expense += amount;
      }
      return { date, income, expense };
    });
  }

  async ensureFolderForPath(filePath) {
    const parts = normalizePath(filePath).split('/');
    parts.pop();
    if (parts.length === 0) return;

    let current = '';
    for (const part of parts) {
      current = current ? `${current}/${part}` : part;
      const exists = await this.app.vault.adapter.exists(current);
      if (!exists) {
        await this.app.vault.createFolder(current);
      }
    }
  }

  async writeVaultFile(path, content) {
    const filePath = normalizePath(path);
    await this.ensureFolderForPath(filePath);
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (file) {
      await this.app.vault.modify(file, content);
    } else {
      await this.app.vault.create(filePath, content);
    }
  }

  generateDashboardMarkdown() {
    const all = this.getSummary();
    const month = this.getCurrentMonthSummary();
    const records = this.getRecords().slice(0, 30);
    const now = new Date().toLocaleString();

    const row = (name, value) => `| ${name} | ${formatMoney(value)} |`;
    const recordRows = records.length
      ? records.map(r => `| ${r.date || ''}${r.time ? ' ' + r.time : ''} | ${this.getTypeLabel(r.type)} | ${formatMoney(r.amount)} | ${r.category || ''} | ${r.person || ''} | ${r.note || ''} |`).join('\n')
      : `| - | - | - | - | - | ${this.t('noRecords')} |`;

    return `# ${this.t('dashboardTitle')}

> ${this.t('autoGenerated')}${now}

## ${this.t('overview')}

| ${this.t('item')} | ${this.t('value')} |
|---|---:|
${row(this.t('currentAccount'), all.currentAccount)}
${row(this.t('expectedExpense'), this.getExpectedExpense())}
${row(this.t('creditCard'), all.creditCard)}
${row(this.t('expense'), all.expense)}
${row(this.t('income'), all.income)}
${row(this.t('loanOut'), all.loanLeft)}

## ${this.t('currentMonth')}

| ${this.t('item')} | ${this.t('value')} |
|---|---:|
${row(this.t('monthlyAccountChange'), month.currentAccount)}
${row(this.t('monthlyCreditChange'), month.creditCard)}
${row(this.t('monthlyExpense'), month.expense)}
${row(this.t('monthlyIncome'), month.income)}
${row(this.t('monthlyLoanLeft'), month.loanLeft)}

## ${this.t('rulesTitle')}

- ${this.t('ruleCurrent')}
- ${this.t('ruleCredit')}
- ${this.t('ruleExpense')}
- ${this.t('ruleLoan')}

## ${this.t('recentRecords')}

| ${this.t('date')} | ${this.t('type')} | ${this.t('amount')} | ${this.t('category')} | ${this.t('person')} | ${this.t('note')} |
|---|---|---:|---|---|---|
${recordRows}
`;
  }

  generateSummaryNoteMarkdown(note) {
    const summary = this.getSummary();
    const title = this.t(note.key);
    const records = this.getRecords().filter(r => note.recordTypes.includes(r.type));
    const now = new Date().toLocaleString();
    const recordRows = records.length
      ? records.map(r => `| ${r.date || ''}${r.time ? ' ' + r.time : ''} | ${this.getTypeLabel(r.type)} | ${formatMoney(r.amount)} | ${r.category || ''} | ${r.person || ''} | ${r.note || ''} |`).join('\n')
      : `| - | - | - | - | - | ${this.t('noRecords')} |`;

    return `# ${title}

> ${this.t('autoGenerated')}${now}

| ${this.t('item')} | ${this.t('value')} |
|---|---:|
| ${title} | ${formatMoney(summary[note.key])} |

## ${this.t('recentRecords')}

| ${this.t('date')} | ${this.t('type')} | ${this.t('amount')} | ${this.t('category')} | ${this.t('person')} | ${this.t('note')} |
|---|---|---:|---|---|---|
${recordRows}
`;
  }

  async updateSummaryNote(note) {
    await this.writeVaultFile(this.getSummaryNotePath(note), this.generateSummaryNoteMarkdown(note));
  }

  async updateAllSummaryNotes() {
    for (const note of SUMMARY_NOTES) {
      await this.updateSummaryNote(note);
    }
  }

  async updateDashboardNote() {
    await this.writeVaultFile(this.getDashboardPath(), this.generateDashboardMarkdown());
  }

  async createOrUpdateCanvas() {
    const canvasGuide = `# ${this.t('canvasGuideTitle')}\n\n1. ${this.t('canvasGuide1')}\n2. ${this.t('canvasGuide2')}\n3. ${this.t('canvasGuide3')}\n\n## ${this.t('typeIntroTitle')}\n\n- ${this.t('guideIncome')}\n- ${this.t('guideExpense')}\n- ${this.t('guideCreditExpense')}\n- ${this.t('guideRepayCredit')}\n- ${this.t('guideLendOut')}\n- ${this.t('guideCollectLoan')}\n- ${this.t('guideAdjust')}`;

    const defaultNodes = [
      {
        id: 'funds-dashboard',
        type: 'file',
        x: 0,
        y: 0,
        width: 620,
        height: 720,
        file: this.getDashboardPath()
      },
      {
        id: 'funds-guide',
        type: 'text',
        x: 660,
        y: 0,
        width: 420,
        height: 340,
        text: canvasGuide
      }
    ];

    const canvasPath = this.getCanvasPath();
    let canvas = { nodes: [], edges: [] };
    if (await this.app.vault.adapter.exists(canvasPath)) {
      try {
        const existing = JSON.parse(await this.app.vault.adapter.read(canvasPath));
        canvas = {
          ...existing,
          nodes: Array.isArray(existing.nodes) ? existing.nodes : [],
          edges: Array.isArray(existing.edges) ? existing.edges : []
        };
      } catch (error) {
        console.error('Personal Funds: failed to read existing canvas, rebuilding default canvas', error);
      }
    }

    const defaultsById = Object.fromEntries(defaultNodes.map(node => [node.id, node]));
    const touched = new Set();
    canvas.nodes = canvas.nodes.map(node => {
      const next = defaultsById[node.id];
      if (!next) return node;
      touched.add(node.id);
      return { ...node, ...next, x: node.x ?? next.x, y: node.y ?? next.y };
    });
    for (const node of defaultNodes) {
      if (!touched.has(node.id)) canvas.nodes.push(node);
    }

    await this.writeVaultFile(canvasPath, JSON.stringify(canvas, null, 2));
  }
};

class ExpectedExpenseModal extends Modal {
  constructor(app, plugin, onSaved) {
    super(app);
    this.plugin = plugin;
    this.onSaved = onSaved;
  }

  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl('h2', { text: this.plugin.t('expectedExpensePrompt') });

    let amountInput;
    new Setting(contentEl)
      .setName(this.plugin.t('expectedExpense'))
      .setDesc(this.plugin.t('expectedExpenseDescription'))
      .addText(text => {
        amountInput = text;
        text.setPlaceholder('0').setValue(String(this.plugin.getManualExpectedExpense()));
        text.inputEl.type = 'number';
        text.inputEl.min = '0';
        text.inputEl.step = '0.01';
        text.inputEl.inputMode = 'decimal';
      });

    const actions = contentEl.createDiv({ cls: 'modal-button-container' });
    const saveButton = actions.createEl('button', { cls: 'mod-cta', text: this.plugin.t('save') });
    saveButton.onclick = async () => {
      await this.plugin.setExpectedExpense(amountInput.getValue());
      new Notice(this.plugin.t('expectedExpenseSaved'));
      this.onSaved?.();
      this.close();
    };
    setTimeout(() => amountInput.inputEl.focus(), 0);
  }

  onClose() {
    this.contentEl.empty();
  }
}

class RecordEntryModal extends Modal {
  constructor(app, plugin, onSaved) {
    super(app);
    this.plugin = plugin;
    this.onSaved = onSaved;
  }

  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass('milin-finance-record-modal');
    contentEl.createEl('h2', { text: this.plugin.t('addRecord') });

    const form = contentEl.createDiv({ cls: 'milin-finance-record-modal-form' });
    const typeSelect = form.createEl('select');
    for (const type of TYPES) {
      const option = typeSelect.createEl('option', { text: type.labels[this.plugin.getLanguage()] || type.labels.zh });
      option.value = type.id;
    }
    const amountInput = form.createEl('input', { attr: { type: 'number', placeholder: this.plugin.t('amount'), min: '0', step: '0.01' } });
    amountInput.inputMode = 'decimal';
    const categorySelect = form.createEl('select');
    for (const category of this.plugin.getCategories()) {
      const option = categorySelect.createEl('option', { text: category });
      option.value = category;
    }
    const personInput = form.createEl('input', { attr: { type: 'text', placeholder: this.plugin.t('personPlaceholder') } });
    const noteInput = form.createEl('input', { attr: { type: 'text', placeholder: this.plugin.t('notePlaceholder') } });

    const actions = contentEl.createDiv({ cls: 'modal-button-container' });
    const saveButton = actions.createEl('button', { cls: 'mod-cta', text: this.plugin.t('save') });
    saveButton.onclick = async () => {
      const amount = Number(amountInput.value);
      if (!amount || amount <= 0) {
        new Notice(this.plugin.t('amountNotice'));
        amountInput.focus();
        return;
      }
      const { date, time } = localDateParts();
      await this.plugin.addRecord({
        id: `${Date.now()}_${Math.random().toString(16).slice(2)}`,
        date,
        time,
        type: typeSelect.value,
        amount,
        category: categorySelect.value,
        person: personInput.value.trim(),
        note: noteInput.value.trim()
      });
      new Notice(this.plugin.t('savedNotice'));
      this.onSaved?.();
      this.close();
    };
    setTimeout(() => amountInput.focus(), 0);
  }

  onClose() {
    this.contentEl.empty();
  }
}

class FixedExpenseModal extends Modal {
  constructor(app, plugin, onSaved) {
    super(app);
    this.plugin = plugin;
    this.onSaved = onSaved;
  }

  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass('milin-finance-record-modal');
    contentEl.createEl('h2', { text: this.plugin.t('fixedExpenseAdd') });
    const form = contentEl.createDiv({ cls: 'milin-finance-record-modal-form' });
    const name = form.createEl('input', { attr: { type: 'text', placeholder: this.plugin.t('fixedExpenseNamePlaceholder') } });
    const amount = form.createEl('input', { attr: { type: 'number', placeholder: this.plugin.t('amount'), min: '0', step: '0.01' } });
    amount.inputMode = 'decimal';
    const note = form.createEl('input', { attr: { type: 'text', placeholder: this.plugin.t('notePlaceholder') } });
    note.style.gridColumn = '1 / -1';
    const actions = contentEl.createDiv({ cls: 'modal-button-container' });
    const save = actions.createEl('button', { cls: 'mod-cta', text: this.plugin.t('save') });
    save.onclick = async () => {
      const value = Number(amount.value);
      if (!name.value.trim() || !value || value <= 0) {
        new Notice(this.plugin.t('amountNotice'));
        return;
      }
      await this.plugin.addFixedExpense({ id: `${Date.now()}_${Math.random().toString(16).slice(2)}`, name: name.value.trim(), amount: value, note: note.value.trim() });
      new Notice(this.plugin.t('fixedExpenseSaved'));
      this.onSaved?.();
      this.close();
    };
    setTimeout(() => name.focus(), 0);
  }

  onClose() { this.contentEl.empty(); }
}

class PersonalFundsSettingTab extends PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }

  display() {
    const { containerEl } = this;
    containerEl.empty();

    new Setting(containerEl)
      .setName(this.plugin.t('databaseFolderName'))
      .setDesc(this.plugin.t('databaseFolderDesc'))
      .addText(text => {
        text
          .setPlaceholder(DEFAULT_DATA_FOLDER)
          .setValue(this.plugin.getDataFolder())
          .onChange(async value => {
            const folder = normalizePath(value.trim() || DEFAULT_DATA_FOLDER).replace(/^\/+|\/+$/g, '');
            this.plugin.data.settings.dataFolder = folder || DEFAULT_DATA_FOLDER;
            await this.plugin.saveData(this.plugin.data);
            await this.plugin.writeDatabase();
            this.plugin.refreshViews();
          });
      });
  }
}

class FinanceView extends ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.activeSection = 'overview';
    this.navigationOpen = false;
    this.recordCategoryFilter = 'all';
    this.recordTypeFilter = 'all';
  }

  getViewType() {
    return VIEW_TYPE_PERSONAL_FUNDS;
  }

  getDisplayText() {
    return this.plugin.t('title');
  }

  getIcon() {
    return 'wallet-cards';
  }

  async onOpen() {
    this.containerEl.addClass('milin-finance-shell');
    this.containerEl.addClass('personal-funds-view-shell');
    this.registerDomEvent(this.contentEl, 'wheel', event => {
      const nestedScroller = event.target.closest?.('.milin-finance-overview-records');
      const scrollTarget = nestedScroller || this.contentEl;
      if (scrollTarget.scrollHeight <= scrollTarget.clientHeight) return;
      scrollTarget.scrollTop += event.deltaY;
      event.preventDefault();
      event.stopPropagation();
    }, { passive: false });
    this.render();
  }

  async onClose() {
    this.contentEl.empty();
    this.containerEl.removeClass('milin-finance-shell');
    this.containerEl.removeClass('personal-funds-view-shell');
  }

  render() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass('milin-finance-modal');
    contentEl.addClass('milin-finance-tab');

    const layout = contentEl.createDiv({ cls: `milin-finance-dashboard-layout ${this.navigationOpen ? 'is-navigation-open' : ''}` });
    this.renderNavigation(layout);
    const workspace = layout.createDiv({ cls: 'milin-finance-workspace' });
    const header = workspace.createDiv({ cls: 'milin-finance-header' });
    header.createEl('h2', { text: this.plugin.t('title') });

    const headerActions = header.createDiv({ cls: 'milin-finance-header-actions' });
    const addToolbarAction = (iconName, label, callback, className = 'milin-finance-toolbar-action') => {
      const button = headerActions.createEl('button', {
        cls: className,
        attr: { type: 'button', title: label, 'aria-label': label }
      });
      setIcon(button, iconName);
      button.onclick = callback;
      return button;
    };
    addToolbarAction('menu', this.plugin.t('navigation'), () => {
      this.navigationOpen = !this.navigationOpen;
      this.render();
    }, 'milin-finance-toolbar-action milin-finance-toolbar-menu');
    const addRecordButton = addToolbarAction('plus', this.plugin.t('addRecord'), () => {
      this.openRecordModal();
    }, 'milin-finance-toolbar-action milin-finance-toolbar-add');
    addRecordButton.createSpan({ text: this.plugin.t('addRecord') });
    addToolbarAction('refresh-cw', this.plugin.t('updateDashboard'), async () => {
      await this.plugin.updateDashboardNote();
      await this.plugin.createOrUpdateCanvas();
      new Notice(this.plugin.t('dashboardUpdatedNotice'));
    });
    addToolbarAction('database', this.plugin.t('readDatabase'), async () => {
      const loaded = await this.plugin.readDatabase();
      if (loaded) {
        new Notice(this.plugin.t('databaseReadNotice'));
        this.render();
      }
    });
    const langBtn = headerActions.createEl('button', {
      cls: 'milin-finance-lang-toggle',
      text: this.plugin.t('languageSwitch'),
      attr: { title: this.plugin.t('switchTitle') }
    });
    langBtn.onclick = async () => {
      await this.plugin.toggleLanguage();
      new Notice(this.plugin.t('languageName'));
      this.render();
    };

    if (this.activeSection === 'overview') {
      this.renderOverviewWorkspace(workspace);
      return;
    }
    if (this.activeSection === 'records') {
      this.renderRecordsWorkspace(workspace);
      return;
    }
    if (this.activeSection === 'expense') {
      this.renderFixedExpenseWorkspace(workspace);
      return;
    }
    this.renderMetricWorkspace(workspace);
  }

  renderNavigation(root) {
    const sections = [
      { id: 'overview', title: this.plugin.t('overview'), icon: 'house' },
      { id: 'records', title: this.plugin.t('recentRecords'), icon: 'notebook-tabs' },
      { id: 'expense', title: this.plugin.t('fixedExpense'), icon: 'calendar-days' },
      { id: 'account', title: this.plugin.t('accountManagement'), icon: 'wallet-cards' }
    ];
    const nav = root.createDiv({ cls: 'milin-finance-nav' });
    for (const section of sections) {
      const item = nav.createEl('button', {
        cls: `milin-finance-nav-item ${this.activeSection === section.id ? 'is-active' : ''}`,
        attr: { type: 'button', 'aria-current': this.activeSection === section.id ? 'page' : 'false' }
      });
      const icon = item.createDiv({ cls: 'milin-finance-nav-icon' });
      setIcon(icon, section.icon);
      const copy = item.createDiv({ cls: 'milin-finance-nav-copy' });
      copy.createDiv({ cls: 'milin-finance-nav-title', text: section.title });
      item.onclick = () => {
        this.activeSection = section.id;
        this.navigationOpen = false;
        this.render();
      };
    }
  }

  renderOverviewWorkspace(root) {
    const summary = this.plugin.getSummary();
    const month = this.plugin.getCurrentMonthSummary();
    const heading = root.createDiv({ cls: 'milin-finance-workspace-heading' });
    heading.createEl('h1', { text: this.plugin.t('overview') });
    heading.createDiv({ cls: 'milin-finance-workspace-subtitle', text: this.plugin.t('accountOverview') });

    const cards = root.createDiv({ cls: 'milin-finance-overview-cards' });
    const items = [
      [this.plugin.t('currentAccount'), summary.currentAccount, 'wallet', 'account'],
      [this.plugin.t('creditDue'), summary.creditCard, 'credit-card', 'credit'],
      [this.plugin.t('monthlyExpense'), month.expense, 'trending-up', 'expense'],
      [this.plugin.t('monthlyIncome'), month.income, 'arrow-down-to-line', 'income'],
      [this.plugin.t('lendingOutstanding'), summary.loanLeft, 'users-round', 'loan']
    ];
    for (const [label, value, iconName, tone] of items) {
      const card = cards.createDiv({ cls: `milin-finance-overview-card milin-finance-overview-card--${tone}` });
      const icon = card.createDiv({ cls: 'milin-finance-overview-icon' });
      setIcon(icon, iconName);
      const copy = card.createDiv({ cls: 'milin-finance-overview-copy' });
      copy.createDiv({ cls: 'milin-finance-overview-label', text: label });
      copy.createDiv({ cls: 'milin-finance-overview-value', text: formatMoney(value) });
    }

    const content = root.createDiv({ cls: 'milin-finance-overview-grid' });
    this.renderOverviewRecentRecords(content);
    this.renderMonthlyTrend(content, month);
  }

  renderOverviewRecentRecords(root) {
    const panel = root.createDiv({ cls: 'milin-finance-panel milin-finance-overview-records' });
    const header = panel.createDiv({ cls: 'milin-finance-panel-title' });
    header.createEl('h3', { text: this.plugin.t('recentRecords') });
    const more = header.createEl('button', { cls: 'milin-finance-panel-link', text: this.plugin.t('viewAll') });
    setIcon(more.createSpan({ cls: 'milin-finance-panel-link-icon' }), 'arrow-right');
    more.onclick = () => { this.activeSection = 'records'; this.render(); };
    const records = this.plugin.getRecords().slice(0, 5);
    if (!records.length) {
      panel.createDiv({ cls: 'milin-finance-empty', text: this.plugin.t('noRecords') });
      return;
    }
    for (const record of records) {
      const row = panel.createDiv({ cls: 'milin-finance-overview-record' });
      const icon = row.createDiv({ cls: `milin-finance-overview-record-icon milin-finance-record-row--${this.plugin.getTypeTone(record.type)}` });
      setIcon(icon, this.recordIcon(record.type));
      const copy = row.createDiv({ cls: 'milin-finance-overview-record-copy' });
      copy.createDiv({ text: record.note || record.category || this.plugin.getTypeLabel(record.type) });
      copy.createDiv({ cls: 'milin-finance-overview-record-type', text: this.plugin.getTypeLabel(record.type) });
      row.createSpan({ cls: 'milin-finance-overview-record-date', text: String(record.date || '').slice(5) });
      const amountText = this.recordAmountText(record);
      const amountTone = amountText.startsWith('+') ? 'is-positive' : amountText.startsWith('-') ? 'is-negative' : '';
      row.createSpan({ cls: `milin-finance-overview-record-value ${amountTone}`, text: amountText });
    }
  }

  renderMonthlyTrend(root, month) {
    const panel = root.createDiv({ cls: 'milin-finance-panel milin-finance-monthly-trend' });
    const header = panel.createDiv({ cls: 'milin-finance-panel-title' });
    header.createEl('h3', { text: this.plugin.t('monthlyTrend') });
    const projection = header.createDiv({ cls: 'milin-finance-monthly-projection' });
    projection.createDiv({ text: `${this.plugin.t('expectedExpense')}：${formatMoney(this.plugin.getExpectedExpense())}` });
    projection.createDiv({ text: `${this.plugin.t('afterExpectedExpense')}：${formatMoney(this.plugin.getSummary().currentAccount - this.plugin.getExpectedExpense())}` });
    const trend = this.plugin.getMonthlyFlowTrend(7);
    const max = Math.max(1, ...trend.flatMap(point => [point.income, point.expense]));
    const pointList = key => trend.map((point, index) => {
      const x = 24 + index * 592 / Math.max(trend.length - 1, 1);
      const y = 186 - point[key] / max * 148;
      return { x, y, point };
    });
    const expensePoints = pointList('expense');
    const incomePoints = pointList('income');
    const chart = panel.createDiv({ cls: 'milin-finance-trend-chart' });
    const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
    svg.setAttribute('viewBox', '0 0 640 235');
    svg.setAttribute('preserveAspectRatio', 'none');
    for (let index = 0; index <= 4; index += 1) {
      const y = 186 - index * 148 / 4;
      const grid = document.createElementNS('http://www.w3.org/2000/svg', 'line');
      grid.setAttribute('class', 'milin-finance-trend-gridline');
      grid.setAttribute('x1', '34'); grid.setAttribute('x2', '616'); grid.setAttribute('y1', y); grid.setAttribute('y2', y);
      svg.appendChild(grid);
      const tick = document.createElementNS('http://www.w3.org/2000/svg', 'text');
      tick.setAttribute('class', 'milin-finance-trend-axis');
      tick.setAttribute('x', '0'); tick.setAttribute('y', y + 4);
      tick.textContent = String(Math.round(max * index / 4));
      svg.appendChild(tick);
    }
    for (const [points, className] of [[expensePoints, 'milin-finance-trend-expense'], [incomePoints, 'milin-finance-trend-income']]) {
      const line = document.createElementNS('http://www.w3.org/2000/svg', 'polyline');
      line.setAttribute('class', className);
      line.setAttribute('points', points.map(point => `${point.x},${point.y}`).join(' '));
      svg.appendChild(line);
      for (const { x, y } of points) {
        const dot = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
        dot.setAttribute('class', className);
        dot.setAttribute('cx', x); dot.setAttribute('cy', y); dot.setAttribute('r', '4.5');
        svg.appendChild(dot);
      }
    }
    for (const { x, point } of incomePoints) {
      const label = document.createElementNS('http://www.w3.org/2000/svg', 'text');
      label.setAttribute('class', 'milin-finance-trend-label');
      label.setAttribute('x', x); label.setAttribute('y', '222'); label.setAttribute('text-anchor', 'middle');
      label.textContent = point.date.slice(5);
      svg.appendChild(label);
    }
    chart.appendChild(svg);
  }

  renderFixedExpenseWorkspace(root) {
    const entries = this.plugin.getFixedExpenses();
    const heading = root.createDiv({ cls: 'milin-finance-workspace-heading' });
    heading.createEl('h1', { text: this.plugin.t('fixedExpense') });
    heading.createDiv({ cls: 'milin-finance-workspace-subtitle', text: this.plugin.t('expectedExpenseDescription') });

    const hero = root.createDiv({ cls: 'milin-finance-hero milin-finance-fixed-expense-hero' });
    const main = hero.createDiv({ cls: 'milin-finance-hero-main' });
    main.createDiv({ cls: 'milin-finance-hero-label', text: this.plugin.t('expectedExpense') });
    main.createDiv({ cls: 'milin-finance-hero-value', text: formatMoney(this.plugin.getExpectedExpense()) });
    const add = hero.createEl('button', { cls: 'milin-finance-fixed-expense-add', text: this.plugin.t('fixedExpenseAdd') });
    setIcon(add.createSpan(), 'plus');
    add.onclick = () => new FixedExpenseModal(this.app, this.plugin, () => this.render()).open();

    const panel = root.createDiv({ cls: 'milin-finance-panel milin-finance-fixed-expense-list' });
    panel.createEl('h3', { text: this.plugin.t('fixedExpense') });
    if (this.plugin.getManualExpectedExpense() > 0) {
      this.renderFixedExpenseRow(panel, { id: 'manual', name: this.plugin.t('expectedExpense'), amount: this.plugin.getManualExpectedExpense(), note: '' }, false);
    }
    if (!entries.length && this.plugin.getManualExpectedExpense() <= 0) {
      panel.createDiv({ cls: 'milin-finance-empty', text: this.plugin.t('fixedExpenseEmpty') });
      return;
    }
    for (const entry of entries) this.renderFixedExpenseRow(panel, entry, true);
  }

  renderFixedExpenseRow(root, entry, canDelete) {
    const row = root.createDiv({ cls: 'milin-finance-fixed-expense-row' });
    const copy = row.createDiv({ cls: 'milin-finance-section-record-copy' });
    copy.createDiv({ cls: 'milin-finance-breakdown-label', text: entry.name });
    if (entry.note) copy.createDiv({ cls: 'milin-finance-section-record-note', text: entry.note });
    row.createSpan({ cls: 'milin-finance-breakdown-value', text: formatMoney(entry.amount) });
    if (canDelete) {
      const remove = row.createEl('button', { cls: 'milin-finance-fixed-expense-delete', attr: { 'aria-label': this.plugin.t('delete') } });
      setIcon(remove, 'trash-2');
      remove.onclick = async () => { await this.plugin.deleteFixedExpense(entry.id); this.render(); };
    }
  }

  renderMetricWorkspace(root) {
    const summary = this.plugin.getSummary();
    const month = this.plugin.getCurrentMonthSummary();
    const section = {
      account: { title: this.plugin.t('currentAccount'), subtitle: this.plugin.t('availableBalance'), value: summary.currentAccount, icon: 'wallet' },
      credit: { title: this.plugin.t('creditCard'), subtitle: this.plugin.t('creditDue'), value: summary.creditCard, icon: 'credit-card' },
      expense: { title: this.plugin.t('expense'), subtitle: this.plugin.t('currentMonthTotal'), value: month.expense, icon: 'trending-up' },
      income: { title: this.plugin.t('income'), subtitle: this.plugin.t('currentMonthTotal'), value: month.income, icon: 'arrow-down-to-line' },
      loan: { title: this.plugin.t('loanOut'), subtitle: this.plugin.t('lendingOutstanding'), value: summary.loanLeft, icon: 'users-round' }
    }[this.activeSection];

    const heading = root.createDiv({ cls: 'milin-finance-workspace-heading' });
    heading.createEl('h1', { text: section.title });
    heading.createDiv({ cls: 'milin-finance-workspace-subtitle', text: section.subtitle });

    const hero = root.createDiv({ cls: 'milin-finance-hero' });
    const heroMain = hero.createDiv({ cls: 'milin-finance-hero-main' });
    heroMain.createDiv({ cls: 'milin-finance-hero-label', text: section.subtitle });
    heroMain.createDiv({ cls: 'milin-finance-hero-value', text: formatMoney(section.value) });
    const heroIcon = hero.createDiv({ cls: 'milin-finance-hero-icon' });
    setIcon(heroIcon, section.icon);

    if (this.activeSection === 'account' || this.activeSection === 'expense') {
      const projection = hero.createDiv({ cls: 'milin-finance-projection' });
      projection.createDiv({ text: `${this.plugin.t('expectedExpense')}：${formatMoney(this.plugin.getExpectedExpense())}` });
      const afterExpected = this.activeSection === 'account' ? section.value - this.plugin.getExpectedExpense() : section.value + this.plugin.getExpectedExpense();
      const projectionLabel = this.activeSection === 'account' ? this.plugin.t('afterExpectedExpense') : this.plugin.t('expectedTotalExpense');
      projection.createDiv({ cls: 'milin-finance-projection-after', text: `${projectionLabel}：${formatMoney(afterExpected)}` });
      hero.onclick = () => this.openExpectedExpenseModal();
      hero.setAttr('title', this.plugin.t('expectedExpensePrompt'));
    }

    const content = root.createDiv({ cls: 'milin-finance-workspace-grid' });
    if (this.activeSection === 'account') {
      this.renderAccountBreakdown(content, summary);
      this.renderBalanceTrend(content);
    } else {
      this.renderSectionDetails(content, section, summary, month);
    }
  }

  renderAccountBreakdown(root, summary) {
    const panel = root.createDiv({ cls: 'milin-finance-panel' });
    panel.createEl('h3', { text: this.plugin.t('accountList') });
    const rows = [
      [this.plugin.t('currentAccount'), summary.currentAccount, 'wallet'],
      [this.plugin.t('afterExpectedExpense'), summary.currentAccount - this.plugin.getExpectedExpense(), 'circle-dollar-sign'],
      [this.plugin.t('creditDue'), summary.creditCard, 'credit-card'],
      [this.plugin.t('lendingOutstanding'), summary.loanLeft, 'users-round']
    ];
    for (const [label, value, iconName] of rows) {
      const row = panel.createDiv({ cls: 'milin-finance-breakdown-row' });
      const icon = row.createDiv({ cls: 'milin-finance-breakdown-icon' });
      setIcon(icon, iconName);
      row.createSpan({ cls: 'milin-finance-breakdown-label', text: label });
      row.createSpan({ cls: 'milin-finance-breakdown-value', text: formatMoney(value) });
    }
  }

  renderBalanceTrend(root) {
    const panel = root.createDiv({ cls: 'milin-finance-panel milin-finance-trend-panel' });
    const title = panel.createDiv({ cls: 'milin-finance-panel-title' });
    title.createEl('h3', { text: this.plugin.t('balanceTrend') });
    title.createSpan({ text: this.plugin.t('recentSevenDays') });
    const points = this.plugin.getBalanceTrend(7);
    const values = points.map(point => point.value);
    const min = Math.min(...values);
    const max = Math.max(...values);
    const range = max - min || 1;
    const chart = panel.createDiv({ cls: 'milin-finance-trend-chart' });
    const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
    svg.setAttribute('viewBox', '0 0 640 260');
    svg.setAttribute('preserveAspectRatio', 'none');
    const coordinates = points.map((point, index) => {
      const x = 24 + (index * 592 / Math.max(points.length - 1, 1));
      const y = 34 + (1 - ((point.value - min) / range)) * 160;
      return { x, y, point };
    });
    const line = document.createElementNS('http://www.w3.org/2000/svg', 'polyline');
    line.setAttribute('class', 'milin-finance-trend-line');
    line.setAttribute('points', coordinates.map(point => `${point.x},${point.y}`).join(' '));
    svg.appendChild(line);
    for (const { x, y, point } of coordinates) {
      const dot = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
      dot.setAttribute('class', 'milin-finance-trend-dot');
      dot.setAttribute('cx', x);
      dot.setAttribute('cy', y);
      dot.setAttribute('r', '5');
      svg.appendChild(dot);
      const label = document.createElementNS('http://www.w3.org/2000/svg', 'text');
      label.setAttribute('class', 'milin-finance-trend-label');
      label.setAttribute('x', x);
      label.setAttribute('y', '230');
      label.setAttribute('text-anchor', 'middle');
      label.textContent = point.date.slice(5);
      svg.appendChild(label);
    }
    chart.appendChild(svg);
  }

  renderSectionDetails(root, section, summary, month) {
    const panel = root.createDiv({ cls: 'milin-finance-panel milin-finance-section-details' });
    panel.createEl('h3', { text: this.plugin.t('accountOverview') });
    const detail = panel.createDiv({ cls: 'milin-finance-section-detail-value', text: formatMoney(section.value) });
    detail.setAttr('data-section', this.activeSection);
    const records = this.plugin.getRecords().filter(record => {
      const types = { credit: ['credit_expense', 'repay_credit'], expense: ['expense', 'credit_expense'], income: ['income'], loan: ['lend_out', 'collect_loan'] };
      return (types[this.activeSection] || []).includes(record.type);
    }).slice(0, 5);
    if (!records.length) {
      panel.createDiv({ cls: 'milin-finance-empty', text: this.plugin.t('noRecords') });
      return;
    }
    for (const record of records) {
      const row = panel.createDiv({ cls: 'milin-finance-breakdown-row' });
      const copy = row.createDiv({ cls: 'milin-finance-section-record-copy' });
      if (this.activeSection === 'loan') {
        copy.createDiv({ cls: 'milin-finance-breakdown-label', text: `${record.date || ''} · ${record.person || this.plugin.t('self')}` });
        copy.createDiv({ cls: 'milin-finance-section-record-note', text: record.note || record.category || this.plugin.t('emptyNote') });
      } else {
        copy.createDiv({ cls: 'milin-finance-breakdown-label', text: `${record.date || ''} · ${this.plugin.getTypeLabel(record.type)}` });
      }
      row.createSpan({ cls: 'milin-finance-breakdown-value', text: formatMoney(record.amount) });
    }
  }

  renderRecordsWorkspace(root) {
    const heading = root.createDiv({ cls: 'milin-finance-workspace-heading' });
    heading.createEl('h1', { text: this.plugin.t('recentRecords') });
    heading.createDiv({ cls: 'milin-finance-workspace-subtitle', text: this.plugin.t('viewDetails') });
    this.renderRecordFilters(root);
    this.renderRecords(root, this.getFilteredRecords());
  }

  getFilteredRecords() {
    return this.plugin.getRecords().filter(record => {
      const typeMatches = this.recordTypeFilter === 'all' || record.type === this.recordTypeFilter;
      const categoryMatches = this.recordCategoryFilter === 'all' || record.category === this.recordCategoryFilter;
      return typeMatches && categoryMatches;
    });
  }

  renderRecordFilters(root) {
    const bar = root.createDiv({ cls: 'milin-finance-record-filters' });
    const typeSelect = bar.createEl('select', { attr: { 'aria-label': this.plugin.t('type') } });
    const allType = typeSelect.createEl('option', { text: this.plugin.t('allRecords') });
    allType.value = 'all';
    for (const type of TYPES) {
      const option = typeSelect.createEl('option', { text: type.labels[this.plugin.getLanguage()] || type.labels.zh });
      option.value = type.id;
    }
    typeSelect.value = this.recordTypeFilter;
    typeSelect.onchange = () => { this.recordTypeFilter = typeSelect.value; this.render(); };

    const categorySelect = bar.createEl('select', { attr: { 'aria-label': this.plugin.t('category') } });
    const allCategory = categorySelect.createEl('option', { text: this.plugin.t('allCategories') });
    allCategory.value = 'all';
    const categories = [...new Set(this.plugin.getRecords().map(record => record.category).filter(Boolean))].sort();
    for (const category of categories) {
      const option = categorySelect.createEl('option', { text: category });
      option.value = category;
    }
    categorySelect.value = this.recordCategoryFilter;
    categorySelect.onchange = () => { this.recordCategoryFilter = categorySelect.value; this.render(); };

    const reset = bar.createEl('button', { cls: 'milin-finance-filter-reset', text: this.plugin.t('resetFilter') });
    reset.onclick = () => { this.recordTypeFilter = 'all'; this.recordCategoryFilter = 'all'; this.render(); };
  }

  openRecordModal() {
    new RecordEntryModal(this.app, this.plugin, () => this.render()).open();
  }

  renderSummary(root) {
    const s = this.plugin.getSummary();
    const box = root.createDiv({ cls: 'milin-finance-summary' });

    this.summaryCard(box, this.plugin.t('currentAccount'), s.currentAccount, 'wallet', 'account', SUMMARY_NOTES[0], `${this.plugin.t('expectedExpense')}：${formatMoney(this.plugin.getExpectedExpense())}`);
    this.summaryCard(box, this.plugin.t('creditCard'), s.creditCard, 'credit-card', 'credit', SUMMARY_NOTES[1]);
    this.summaryCard(box, this.plugin.t('expense'), s.expense, 'trending-down', 'expense', SUMMARY_NOTES[2], null, () => this.openExpectedExpenseModal());
    this.summaryCard(box, this.plugin.t('income'), s.income, 'trending-up', 'income', SUMMARY_NOTES[3]);
    this.summaryCard(box, this.plugin.t('loanOut'), s.loanLeft, 'user-round-plus', 'loan', SUMMARY_NOTES[4]);
  }

  summaryCard(root, title, value, iconName, tone, note, subValue, onClick) {
    const text = formatMoney(value);
    const card = root.createDiv({ cls: `milin-finance-card milin-finance-card--${tone}` });
    card.setAttr('role', 'button');
    card.setAttr('tabindex', '0');
    card.setAttr('aria-label', `${title}: ${text}`);
    card.setAttr('title', onClick ? this.plugin.t('expectedExpensePrompt') : this.plugin.getSummaryNotePath(note));
    card.onclick = onClick || (() => this.plugin.openSummaryNote(note));
    card.onkeydown = event => {
      if (event.key === 'Enter' || event.key === ' ') {
        event.preventDefault();
        if (onClick) onClick();
        else this.plugin.openSummaryNote(note);
      }
    };

    const iconWrap = card.createDiv({ cls: 'milin-finance-card-icon' });
    setIcon(iconWrap, iconName);

    card.createDiv({ cls: 'milin-finance-card-title', text: title });
    const valueEl = card.createDiv({ cls: 'milin-finance-card-value', text });
    valueEl.style.setProperty('--milin-value-size', valueFontSize(text));
    if (subValue) {
      card.createDiv({ cls: 'milin-finance-card-subvalue', text: subValue });
    }
  }

  openExpectedExpenseModal() {
    new ExpectedExpenseModal(this.app, this.plugin, () => this.render()).open();
  }

  renderForm(root) {
    const form = root.createDiv({ cls: 'milin-finance-form' });

    const typeSelect = form.createEl('select', { cls: 'milin-finance-control milin-finance-type' });
    for (const t of TYPES) {
      const opt = typeSelect.createEl('option', { text: t.labels[this.plugin.getLanguage()] || t.labels.zh });
      opt.value = t.id;
    }

    const amountInput = form.createEl('input', {
      cls: 'milin-finance-control milin-finance-amount',
      attr: { type: 'number', placeholder: this.plugin.t('amount') }
    });
    amountInput.inputMode = 'decimal';

    const categorySelect = form.createEl('select', { cls: 'milin-finance-control milin-finance-category' });
    for (const c of this.plugin.getCategories()) {
      const opt = categorySelect.createEl('option', { text: c });
      opt.value = c;
    }

    const personInput = form.createEl('input', {
      cls: 'milin-finance-control milin-finance-person',
      attr: { type: 'text', placeholder: this.plugin.t('personPlaceholder') }
    });

    const noteInput = form.createEl('input', {
      cls: 'milin-finance-control milin-finance-note',
      attr: { type: 'text', placeholder: this.plugin.t('notePlaceholder') }
    });

    const saveBtn = form.createEl('button', { cls: 'milin-finance-save', text: this.plugin.t('save') });

    saveBtn.onclick = async () => {
      const amount = Number(amountInput.value);
      if (!amount || amount <= 0) {
        new Notice(this.plugin.t('amountNotice'));
        amountInput.focus();
        return;
      }

      const { date, time } = localDateParts();
      await this.plugin.addRecord({
        id: `${Date.now()}_${Math.random().toString(16).slice(2)}`,
        date,
        time,
        type: typeSelect.value,
        amount,
        category: categorySelect.value,
        person: personInput.value.trim(),
        note: noteInput.value.trim()
      });

      new Notice(this.plugin.t('savedNotice'));
      this.render();
    };
  }

  renderCanvasActions(root) {
    const box = root.createDiv({ cls: 'milin-finance-actions' });

    const dashboardBtn = box.createEl('button', { cls: 'milin-finance-action', text: this.plugin.t('updateDashboard') });
    const docIcon = dashboardBtn.createSpan({ cls: 'milin-finance-action-icon' });
    setIcon(docIcon, 'file-text');
    dashboardBtn.prepend(docIcon);
    dashboardBtn.onclick = async () => {
      await this.plugin.updateDashboardNote();
      new Notice(this.plugin.t('dashboardUpdatedNotice'));
    };

    const canvasBtn = box.createEl('button', { cls: 'milin-finance-action', text: this.plugin.t('createCanvas') });
    const canvasIcon = canvasBtn.createSpan({ cls: 'milin-finance-action-icon' });
    setIcon(canvasIcon, 'layout-grid');
    canvasBtn.prepend(canvasIcon);
    canvasBtn.onclick = async () => {
      await this.plugin.updateDashboardNote();
      await this.plugin.createOrUpdateCanvas();
      new Notice(this.plugin.t('canvasUpdatedNotice'));
    };

    const readBtn = box.createEl('button', { cls: 'milin-finance-action', text: this.plugin.t('readDatabase') });
    const readIcon = readBtn.createSpan({ cls: 'milin-finance-action-icon' });
    setIcon(readIcon, 'database');
    readBtn.prepend(readIcon);
    readBtn.onclick = async () => {
      const loaded = await this.plugin.readDatabase();
      if (loaded) {
        new Notice(this.plugin.t('databaseReadNotice'));
        this.render();
      }
    };
  }

  renderRecords(root, sourceRecords = this.plugin.getRecords()) {
    const records = sourceRecords.slice(0, 30);
    const top = root.createDiv({ cls: 'milin-finance-record-head' });
    top.createEl('h3', { text: this.plugin.t('recentRecords') });
    const count = top.createDiv({ cls: 'milin-finance-record-count' });
    setIcon(count, 'clock-3');
    count.createSpan({ text: this.plugin.t('recordCount', records.length) });

    const list = root.createDiv({ cls: 'milin-finance-records' });

    if (records.length === 0) {
      list.createDiv({ cls: 'milin-finance-empty', text: this.plugin.t('noRecords') });
      return;
    }

    for (const r of records) {
      const row = list.createDiv({ cls: `milin-finance-record-row milin-finance-record-row--${this.plugin.getTypeTone(r.type)}` });
      const typeLabel = this.plugin.getTypeLabel(r.type);
      const tone = this.plugin.getTypeTone(r.type);

      const icon = row.createDiv({ cls: 'milin-finance-record-icon' });
      setIcon(icon, this.recordIcon(r.type));

      const dt = row.createDiv({ cls: 'milin-finance-record-date', text: `${r.date || ''}${r.time ? ' ' + r.time : ''}` });
      dt.setAttr('title', `${r.date || ''}${r.time ? ' ' + r.time : ''}`);

      row.createDiv({ cls: `milin-finance-badge milin-finance-badge--${tone}`, text: typeLabel });

      row.createDiv({ cls: `milin-finance-record-amount milin-finance-record-amount--${tone}`, text: this.recordAmountText(r) });

      const category = row.createDiv({ cls: 'milin-finance-record-meta' });
      setIcon(category, 'utensils');
      category.createSpan({ text: r.category || this.plugin.t('uncategorized') });

      const person = row.createDiv({ cls: 'milin-finance-record-meta' });
      setIcon(person, 'user-round');
      person.createSpan({ text: r.person || this.plugin.t('self') });

      const note = row.createDiv({ cls: 'milin-finance-record-note' });
      setIcon(note, 'message-square');
      note.createSpan({ text: r.note || this.plugin.t('emptyNote') });

      const del = row.createEl('button', { cls: 'milin-finance-delete', attr: { 'aria-label': this.plugin.t('delete') } });
      setIcon(del, 'trash-2');
      del.onclick = async () => {
        await this.plugin.deleteRecord(r.id);
        new Notice(this.plugin.t('deletedNotice'));
        this.render();
      };
    }

    const tip = root.createDiv({ cls: 'milin-finance-tip' });
    setIcon(tip, 'info');
    tip.createSpan({ text: this.plugin.t('tip') });
  }

  recordIcon(type) {
    if (type === 'income' || type === 'collect_loan') return 'arrow-up';
    if (type === 'expense' || type === 'credit_expense' || type === 'repay_credit' || type === 'lend_out') return 'arrow-down';
    return 'equal';
  }

  recordAmountText(record) {
    const amount = Number(record.amount || 0);
    if (record.type === 'income' || record.type === 'collect_loan' || record.type === 'account_adjust') {
      return signedMoney(amount);
    }
    return signedMoney(-amount);
  }
}
